### ISSUE TITLE
Building SVT-HEVC does not work

### ISSUE THREAD

**Issue by BlackScreen** [jb-alvarado/media-autobuild_suite#1256] opened 2019-06-18 06:20 UTC
```
08:09:40   Running git clone for SVT-HEVC...
08:09:45 ┌ SVT-HEVC git ............................. [Recently updated]
08:09:45 ├ Running uninstall...
08:09:59 ├ Running cmake...
08:10:11 ├ Running build...
Likely error:
C:/AB-Suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: use the --help option for usage information
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
[1/1] Linking C executable ..\Bin\Release\SvtHevcEncApp.exe
FAILED: ../Bin/Release/SvtHevcEncApp.exe
cmd.exe /C "cd . && C:\AB-Suite\msys64\mingw64\bin\gcc.exe -mthreads -mtune=generic -O2 -pipe -Wall -Wextra -Wformat -Wformat-security -fstack-protector-strong -fvisibility=hidden -fPIE -fPIC -D_FORTIFY_SOURCE=2 -fno-asynchronous-unwind-tables -O3 -DNDEBUG -O2 -O3  -pipe -static-libgcc -static-libstdc++ -z noexecstack -z relro -z now -pie Source/App/CMakeFiles/SvtHevcEncApp.dir/EbAppConfig.c.o Source/App/CMakeFiles/SvtHevcEncApp.dir/EbAppContext.c.o Source/App/CMakeFiles/SvtHevcEncApp.dir/EbAppFifo.c.o Source/App/CMakeFiles/SvtHevcEncApp.dir/EbAppMain.c.o Source/App/CMakeFiles/SvtHevcEncApp.dir/EbAppProcessCmd.c.o Source/App/CMakeFiles/SvtHevcEncApp.dir/EbTime.c.o Source/App/CMakeFiles/SvtHevcEncApp.dir/EbAppInputy4m.c.o  -o ..\Bin\Release\SvtHevcEncApp.exe -Wl,--major-image-version,0,--minor-image-version,0  ../Bin/Release/libSvtHevcEnc.dll.a -lpthread -lrt -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
C:/AB-Suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: unrecognized option '-z'
C:/AB-Suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: use the --help option for usage information
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
build failed. Check C:/AB-Suite/build/SVT-HEVC-git/build-64bit/ab-suite.build.log
This is required for other packages, so this script will exit.
08:11:29   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/zeWT.zip
Copy and paste [logs.zip](https://0x0.st/zeWT.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
```

**Comment by 1480c1** [comment] 2019-06-18 06:29
I have a suspicion that either the patches did not fully apply or the suite is missing `-DUNIX=OFF‘ somewhere

**Comment by BlackScreen** [comment] 2019-06-18 06:30
> I have a suspicion that either the patches did not fully apply or the suite is missing `-DUNIX=OFF‘ somewhere

Ok. Can I help you checking that?

**Comment by 1480c1** [comment] 2019-06-18 06:30
Can you upload cmake.log?

**Comment by 1480c1** [comment] 2019-06-18 06:31
I'm having trouble accessing zip files from phone

**Comment by 1480c1** [comment] 2019-06-18 06:36
Did you update to latest suite? Latest commit fixed some issue

**Comment by BlackScreen** [comment] 2019-06-18 06:36
The files in "SVT-HEVC-git\build-64bit\CMakeFiles" are attached here.
[CMakeError.log](https://github.com/jb-alvarado/media-autobuild_suite/files/3300070/CMakeError.log)
[CMakeOutput.log](https://github.com/jb-alvarado/media-autobuild_suite/files/3300071/CMakeOutput.log)

**Comment by 1480c1** [comment] 2019-06-18 06:39
Looking at cmake.log, it is missing the flag to turn UNIX off

**Comment by 1480c1** [comment] 2019-06-18 06:40
I ment the ab suite one, I'll check why

**Comment by BlackScreen** [comment] 2019-06-18 06:44
"SVT-HEVC-git\build-64bit" probably then... ;)
[ab-suite.build.log](https://github.com/jb-alvarado/media-autobuild_suite/files/3300105/ab-suite.build.log)
[ab-suite.cmake.log](https://github.com/jb-alvarado/media-autobuild_suite/files/3300106/ab-suite.cmake.log)

**Comment by 1480c1** [comment] 2019-06-18 06:51
try seeing if that pr can fix the problem. If you do not know how to use it, do ask / search up if you want

**Comment by BlackScreen** [comment] 2019-06-18 06:56
> try seeing if that pr can fix the problem. If you do not know how to use it, do ask / search up if you want

I don't know how to test it elegantly, but I just have edited the changes by hand and am running the suite again... Let's see if it works.

**Comment by BlackScreen** [comment] 2019-06-18 06:59
```
08:57:08   Running git update for SVT-HEVC...
08:57:09 ┌ SVT-HEVC git ............................. [Recently updated]
08:57:21 ├ Running cmake...
08:57:37 ├ Running build...
08:59:06 ├ Running install...
08:59:06 ├ Stripping...
08:59:07 └ SVT-HEVC-git ...................................... [Updated]
```
Working. Thanks!

**Comment by 1480c1** [comment] 2019-06-18 07:02
Nice, but it is best to not close the issue until the problem is properly fixed in master branch (merged) that way someone else who might have the same problem before the pr is merged can see this issue and not create a duplicate

**Comment by BlackScreen** [comment] 2019-06-18 07:03
Ok, sorry for closing.
One questing left though: Would it be possible to support SVT-HEVC in FFmpeg?
I have found these patches: https://github.com/OpenVisualCloud/SVT-HEVC/tree/master/ffmpeg_plugin

**Comment by 1480c1** [comment] 2019-06-18 07:04
That is a consideration, although right now, I'm focusing on linking SVT-HEVC with x265 since that is already a feature request.

It might be easy though, let me see

**Comment by 1480c1** [comment] 2019-06-18 07:06
They do keep ffmpeg patches in a folder under `ffmpeg_patches` folder in the repo, so it actually might be easy to do, although problem is is the suite's ffmpeg building code is a bit of a spaghetti

**Comment by BlackScreen** [comment] 2019-06-18 07:08
Ok. It would be cool, but not prio 1. Integrating it with x265 would be a cool first step. :)

**Comment by 1480c1** [comment] 2019-06-18 07:10
To add on for future consideration, the patches from the SVT team are all based on ffmpeg 4.1 branch, at least the ones in the repo, maybe need to make sure they apply cleanly with the master branch

**Comment by wiiaboo** [comment] 2019-06-18 08:43
If it's adding new stuff, it shouldn't be a big issue to keep rebasing it.

**Closed** 2019-06-18 12:52 UTC
