### ISSUE TITLE
Shaderc fails to compile : fatal error: message.h,  no such file or directory.

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#896] opened 2018-08-16 22:09 UTC
At least for 32 bit, which still uses GCC 7.3.0, SHADERC fails to compile (I didn't try 64 bit yet).
Full log at https://0x0.st/sJYj.zip

```
[244/332] Linking CXX static library third_party\spirv-tools\source\opt\libSPIRV-Tools-opt.a
[245/332] Linking CXX executable third_party\spirv-tools\tools\spirv-val.exe
[246/332] Building CXX object third_party/spirv-tools/tools/CMakeFiles/spirv-stats.dir/stats/spirv_stats.cpp.o
[247/332] Building CXX object third_party/glslang/SPIRV/CMakeFiles/SPIRV.dir/Logger.cpp.o
[248/332] Building CXX object third_party/glslang/SPIRV/CMakeFiles/SPIRV.dir/SpvPostProcess.cpp.o
[249/332] Linking CXX executable third_party\spirv-tools\examples\cpp-interface\spirv-tools-cpp-example.exe
[250/332] Building CXX object third_party/glslang/SPIRV/CMakeFiles/SPIRV.dir/GlslangToSpv.cpp.o
FAILED: third_party/glslang/SPIRV/CMakeFiles/SPIRV.dir/GlslangToSpv.cpp.o
H:\Mingw648\msys64\mingw32\bin\c++.exe  -DAMD_EXTENSIONS -DENABLE_HLSL -DENABLE_OPT=1 -DGLSLANG_OSINCLUDE_WIN32 -DNV_EXTENSIONS -I../third_party/glslang/SPIRV/.. -I../third_party/spirv-tools/include -I../third_party/spirv-tools/source -I../third_party/glslang/SPIRV/../External -I../third_party/glslang/glslang/.. -I../third_party/spirv-headers/include -mthreads -mtune=generic -O2 -pipe -O3 -DNDEBUG   -w -Wall -Wmaybe-uninitialized -Wuninitialized -Wunused -Wunused-local-typedefs -Wunused-parameter -Wunused-value -Wunused-variable -Wunused-but-set-parameter -Wunused-but-set-variable -fno-exceptions -Wno-reorder -std=c++11 -MD -MT third_party/glslang/SPIRV/CMakeFiles/SPIRV.dir/GlslangToSpv.cpp.o -MF third_party\glslang\SPIRV\CMakeFiles\SPIRV.dir\GlslangToSpv.cpp.o.d -o third_party/glslang/SPIRV/CMakeFiles/SPIRV.dir/GlslangToSpv.cpp.o -c ../third_party/glslang/SPIRV/GlslangToSpv.cpp
../third_party/glslang/SPIRV/GlslangToSpv.cpp:59:14: fatal error: message.h: No such file or directory
     #include "message.h"
              ^~~~~~~~~~~
compilation terminated.
[251/332] Building CXX object third_party/glslang/SPIRV/CMakeFiles/SPIRV.dir/InReadableOrder.cpp.o
[252/332] Building CXX object third_party/glslang/SPIRV/CMakeFiles/SPIRV.dir/doc.cpp.o
[253/332] Building CXX object third_party/spirv-tools/tools/CMakeFiles/spirv-stats.dir/stats/stats_analyzer.cpp.o
[254/332] Building CXX object third_party/glslang/SPIRV/CMakeFiles/SPIRV.dir/disassemble.cpp.o
[255/332] Building CXX object third_party/spirv-tools/tools/CMakeFiles/spirv-opt.dir/opt/opt.cpp.o
[256/332] Building CXX object third_party/spirv-tools/source/link/CMakeFiles/SPIRV-Tools-link.dir/linker.cpp.o
[257/332] Building CXX object third_party/glslang/SPIRV/CMakeFiles/SPIRV.dir/SpvBuilder.cpp.o
ninja: build stopped: subcommand failed.
[1/80] Check copyright
[2/80] Update build-version.inc in the Shaderc build directory (if necessary).
[3/80] cmd.exe /C "cd /D H:\Mingw648\build\shaderc-git\build-32bit\third_party\spirv-tools && H:\Mingw648\msys64\mingw32\bin\cmake.exe -DCHANGES_FILE=H:/Mingw648/build/shaderc-git/third_party/spirv-tools/CHANGES -DTEMPLATE_FILE=H:/Mingw648/build/shaderc-git/third_party/spirv-tools/cmake/SPIRV-Tools-shared.pc.in -DOUT_FILE=H:/Mingw648/build/shaderc-git/build-32bit/third_party/spirv-tools/SPIRV-Tools-shared.pc -DCMAKE_INSTALL_PREFIX=H:/Mingw648/local32 -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_INSTALL_INCLUDEDIR=include -DSPIRV_SHARED_LIBRARIES=-lSPIRV-Tools-shared -P H:/Mingw648/build/shaderc-git/third_party/spirv-tools/cmake/write_pkg_config.cmake"
[4/80] cmd.exe /C "cd /D H:\Mingw648\build\shaderc-git\build-32bit\third_party\spirv-tools && H:\Mingw648\msys64\mingw32\bin\cmake.exe -DCHANGES_FILE=H:/Mingw648/build/shaderc-git/third_party/spirv-tools/CHANGES -DTEMPLATE_FILE=H:/Mingw648/build/shaderc-git/third_party/spirv-tools/cmake/SPIRV-Tools.pc.in -DOUT_FILE=H:/Mingw648/build/shaderc-git/build-32bit/third_party/spirv-tools/SPIRV-Tools.pc -DCMAKE_INSTALL_PREFIX=H:/Mingw648/local32 -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_INSTALL_INCLUDEDIR=include "-DSPIRV_LIBRARIES=-lSPIRV-Tools -lSPIRV-Tools-link -lSPIRV-Tools-opt" -P H:/Mingw648/build/shaderc-git/third_party/spirv-tools/cmake/write_pkg_config.cmake"
[5/80] Linking CXX static library third_party\spirv-tools\source\link\libSPIRV-Tools-link.a
[6/80] Linking CXX executable third_party\spirv-tools\tools\spirv-link.exe
[7/80] Linking CXX executable third_party\spirv-tools\tools\spirv-stats.exe
[8/80] Linking CXX executable third_party\spirv-tools\tools\spirv-opt.exe
[9/80] Building CXX object third_party/glslang/SPIRV/CMakeFiles/SPIRV.dir/GlslangToSpv.cpp.o
FAILED: third_party/glslang/SPIRV/CMakeFiles/SPIRV.dir/GlslangToSpv.cpp.o
H:\Mingw648\msys64\mingw32\bin\c++.exe  -DAMD_EXTENSIONS -DENABLE_HLSL -DENABLE_OPT=1 -DGLSLANG_OSINCLUDE_WIN32 -DNV_EXTENSIONS -I../third_party/glslang/SPIRV/.. -I../third_party/spirv-tools/include -I../third_party/spirv-tools/source -I../third_party/glslang/SPIRV/../External -I../third_party/glslang/glslang/.. -I../third_party/spirv-headers/include -mthreads -mtune=generic -O2 -pipe -O3 -DNDEBUG   -w -Wall -Wmaybe-uninitialized -Wuninitialized -Wunused -Wunused-local-typedefs -Wunused-parameter -Wunused-value -Wunused-variable -Wunused-but-set-parameter -Wunused-but-set-variable -fno-exceptions -Wno-reorder -std=c++11 -MD -MT third_party/glslang/SPIRV/CMakeFiles/SPIRV.dir/GlslangToSpv.cpp.o -MF third_party\glslang\SPIRV\CMakeFiles\SPIRV.dir\GlslangToSpv.cpp.o.d -o third_party/glslang/SPIRV/CMakeFiles/SPIRV.dir/GlslangToSpv.cpp.o -c ../third_party/glslang/SPIRV/GlslangToSpv.cpp
../third_party/glslang/SPIRV/GlslangToSpv.cpp:59:14: fatal error: message.h: No such file or directory
     #include "message.h"
              ^~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
This is required for other packages, so this script will exit.
  Creating diagnostics file in shaderc-git

All relevant logs have been anonymously uploaded to https://0x0.st/sJYj.zip
Copy and paste [logs.zip](https://0x0.st/sJYj.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by dotansimha** [comment] 2018-08-17 13:34
Same here with 64-bit (windows 10). I opened an issue: https://github.com/jb-alvarado/media-autobuild_suite/issues/895 and @wiiaboo closed it...

**Comment by wiiaboo** [comment] 2018-08-17 14:45
I'm not responsible for fixing broken upstreams. At most I'd force it to use an older commit that someone knows works.

If I can't reproduce the issue on my side, I'm not wasting my free time doing other people's dayjobs (Google).

Report it upstream or give me a working commit hash.

**Closed by wiiaboo** 2018-08-17 14:45 UTC
