### ISSUE TITLE
srt >= 1.3.0 not found using pkg-config

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#906] opened 2018-09-02 13:06 UTC
The ffmpeg sources are now updated to support (and require) a newer libsrt generation than the previously locked revision.

You can probably revert https://github.com/jb-alvarado/media-autobuild_suite/commit/29986f47992d4fe16b2385f5dd379d9178002ad9 (remove the `#commit=1367914ea` part in build/media-suite_compile.sh line 1358).

You may also have to delete _{some of build/srt-git and local*/lib/libsrt.a and local*/lib/pkgconfig/*srt.pc}_ to force an update and rebuild after this library was commit-locked once.

**Comment by LigH-de** [comment] 2018-09-02 14:06
I fear it's more complicated...

```
┌ srt git ........................................... [Recently updated]
sed: can't read scripts/haisrt.pc.in: No such file or directory
├ Running cmake...
Likely error:
  <thread>.  FIX IF POSSIBLE.


CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
PTHREAD_LIBRARY
    linked by target "srt_static" in directory H:/development/media-autobuild_suite-master/build/srt-git

-- Configuring incomplete, errors occurred!
```

What's missing from ab-suite.cmake.log:
```
-- C++ VERSION: Setting C++11 compat flag for gnu compiler
CMake Warning at CMakeLists.txt:629 (message):
  On MinGW, C++11 apps are blocked due to lacking proper C++11 headers for
  <thread>.  FIX IF POSSIBLE.
```

Hooray. No more libsrt for MinGW.

**Comment by wiiaboo** [comment] 2018-09-02 20:54
Fixed with a patch and lots of retries, but didn't test actually running the apps since I have no idea what they're even used for.

**Closed by wiiaboo** 2018-09-02 20:54 UTC

**Comment by wiiaboo** [comment] 2018-09-02 20:56
I doubt upstream will accept these, since I have a PR stuck for months there.

**Comment by wpapp** [comment] 2018-09-06 02:35
It is still unsolved

**Comment by schmidthubert** [comment] 2018-09-06 02:47
Just wait for a new patch or meanwhile [help yourself](https://github.com/jb-alvarado/media-autobuild_suite/commit/fc646c18c3094ef75fa70e27aed54c9adf369d79) ...

**Comment by wpapp** [comment] 2018-09-06 09:31
Oh,I'm sorry.

**Comment by LigH-de** [comment] 2018-09-06 09:52
I am the one who tries to compile "everything" occasionally (and keeps bugging wiiaboo with issues related to "never used" libraries).

And right now, I have [a bunch of new configure errors](https://pastebin.com/vZWhefRY) but the reason is somewhere in a Bermuda polygon between MABS, MSYS2, liblensfun, ffmpeg, and who knows, all trying to pach from different sides, leaving us in the crossfire...

**Comment by schmidthubert** [comment] 2018-09-06 10:03
You should backup your stuff now and then ... :+1:

**Comment by wiiaboo** [comment] 2018-09-06 10:04
OK, so the issue is definitely on upstream, since the internal libs objects aren't being added to the public libs by meson. I'm definitely not compiling meson/glib just to fix this.
