### ISSUE TITLE
ffmpeg fails

### ISSUE THREAD

**Issue by toddcbryant** [jb-alvarado/media-autobuild_suite#180] opened 2015-10-13 01:04 UTC
I am trying to compile x64 only with both static and shared.   I have tried this on several machines and always get this error.

library.mak:111: recipe for target 'libavformat/avformat-57.dll' failed

log of ffmpeg below

abrreviated.

http://sprunge.us/KTYg

**Comment by wiiaboo** [comment] 2015-10-13 01:37
I can reproduce it.

**Comment by wiiaboo** [comment] 2015-10-13 17:07
Looks like shared FFmpeg doesn't like mingw freetype/harfbuzz/libopus so we'll have to go back to compiling those ourselves...

**Comment by wiiaboo** [comment] 2015-10-13 17:44
Check if latest commit fixes it.

**Comment by toddcbryant** [comment] 2015-10-13 21:42
If you only choose static it works.  If you want "shared and static" it fails with the same error

**Comment by wiiaboo** [comment] 2015-10-13 21:42
Should be fixed now. At least it works with me.

**Comment by toddcbryant** [comment] 2015-10-14 03:38
I cleaned up everything and started from scratch and it works great.  Question?  If I make some changes to x264, how can I re-compile x264 and FFMPEG with my x264 changes?

**Closed** 2015-10-14 03:38 UTC
Labels: bug

**Comment by wiiaboo** [comment] 2015-10-14 11:49
The better way would be changing the script to add a patch with your changes (using `do_patch <patch_name>` before the `configure` commands) or use a different repository/branch.

You can also apply your changes, compile and install x264 yourself and disable the script's so your changes don't get overwritten and add `--enable-libx264` to `ffmpeg_options.txt` so it's also included in FFmpeg, if you want.
