### ISSUE TITLE
ffmpeg fails with latest x265 -> ffmpeg config does not find x265

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#632] opened 2017-11-11 19:12 UTC
These are the last lines from output from ffmpeg configure:
```
require_pkg_config libx265 x265 x265.h x265_api_get
check_pkg_config libx265 x265 x265.h x265_api_get
test_pkg_config libx265 x265 x265.h x265_api_get
pkg-config --exists --print-errors x265
check_func_headers x265.h x265_api_get -LK:/Mingw6461/local32/lib -lx265 -lstdc++ -lgcc -lgcc_eh -lgcc -lgcc_eh
check_ld cc -LK:/Mingw6461/local32/lib -lx265 -lstdc++ -lgcc -lgcc_eh -lgcc -lgcc_eh
check_cc -LK:/Mingw6461/local32/lib
BEGIN /tmp/ffconf.v2Zp9sfm/test.c
    1	#include <x265.h>
    2	#include <stdint.h>
    3	long check_x265_api_get(void) { return (long) x265_api_get; }
    4	int main(void) { int ret = 0;
    5	 ret |= ((intptr_t)check_x265_api_get) & 0xFFFF;
    6	return ret; }
END /tmp/ffconf.v2Zp9sfm/test.c
gcc -D_FORTIFY_SOURCE=2 -D__USE_MINGW_ANSI_STDIO=1 -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -U__STRICT_ANSI__ -D__USE_MINGW_ANSI_STDIO=1 -D__printf__=__gnu_printf__ -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -DOPJ_STATIC -mthreads -O2 -mtune=native -pipe -DLIBTWOLAME_STATIC -DCACA_STATIC -DMODPLUG_STATIC -DCHROMAPRINT_NODLL -DZMQ_STATIC -DPTW32_STATIC_LIB -DKVZ_STATIC_LIB -Wno-deprecated-declarations -Wno-incompatible-pointer-types -Wno-redundant-decls -fno-tree-vectorize -mstackrealign -mfpmath=sse -mmmx -msse -msse2 -march=i686 -std=c11 -fomit-frame-pointer -pthread -IK:/Mingw6461/local32/include/harfbuzz -IK:/Mingw6461/local32/include/fribidi -IK:/Mingw6461/local32/include/freetype2 -IK:/Mingw6461/local32/include/bs2b -IK:/Mingw6461/local32/include/freetype2 -IK:/Mingw6461/local32/include/fribidi -IK:/Mingw6461/msys64/mingw32/include/libmodplug -IK:/Mingw6461/msys64/mingw32/include/openjpeg-2.3 -IK:/Mingw6461/local32/include/opus -IK:/Mingw6461/local32/include/opus -IK:/Mingw6461/local32/include/rubberband -LK:/Mingw6461/local32/lib -c -o /tmp/ffconf.v2Zp9sfm/test.o /tmp/ffconf.v2Zp9sfm/test.c
In file included from K:/Mingw6461/msys64/tmp/ffconf.v2Zp9sfm/test.c:1:0:
K:/Mingw6461/local32/include/x265.h:1753:40: error: expected ';', ',' or ')' before '&' token
 FILE* x265_csvlog_open(const x265_param& param);
                                        ^
K:/Mingw6461/local32/include/x265.h:1757:40: error: expected ';', ',' or ')' before '&' token
 void x265_csvlog_frame(const x265_param& param, const x265_picture& pic);
                                        ^
K:/Mingw6461/local32/include/x265.h:1762:64: error: expected ';', ',' or ')' before '&' token
 void x265_csvlog_encode(x265_encoder *encoder, const x265_stats& stats, int argc, char** argv);
                                                                ^
K:/Mingw6461/local32/include/x265.h:1766:36: error: expected ';', ',' or ')' before '&' token
 void x265_dither_image(x265_picture& pic, int picWidth, int picHeight, int16_t *errorBuf, int bitDepth);
                                    ^
K:/Mingw6461/local32/include/x265.h:1815:50: error: expected ';', ',' or ')' before '&' token
     FILE*         (*csvlog_open)(const x265_param&);
                                                  ^
K:/Mingw6461/local32/include/x265.h:1816:51: error: expected ';', ',' or ')' before '&' token
     void          (*csvlog_frame)(const x265_param&, const x265_picture&);
                                                   ^
K:/Mingw6461/local32/include/x265.h:1817:67: error: expected ';', ',' or ')' before '&' token
     void          (*csvlog_encode)(x265_encoder*, const x265_stats&, int, char**);
                                                                   ^
K:/Mingw6461/local32/include/x265.h:1818:47: error: expected ';', ',' or ')' before '&' token
     void          (*dither_image)(x265_picture&, int, int, int16_t*, int);
                                               ^
K:/Mingw6461/local32/include/x265.h:1820:1: warning: no semicolon at end of struct or union
 } x265_api;
 ^
ERROR: x265 not found using pkg-config
```

**Comment by GDXN** [comment] 2017-11-12 02:49
Its ffmpeg related, some changes in the code that make the header file a not valid c header, only a valid cpp header.

**Comment by Metaphorce812** [comment] 2017-11-12 04:16
Same problem here. [logs.zip](https://0x0.st/siiz.zip)
```
┌ ffmpeg git ........................................... [Files missing]
├ Changing options to comply to nonfree...
├ Compiling static FFmpeg...
├ Running configure...
Likely error:
CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++ -L/local64/lib -L/mingw64/lib
../configure --prefix=/local64 --bindir=/local64/bin-video --pkg-config-flags=--static --enable-avisynth --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-cuda --enable-cuvid --enable-decklink --enable-fontconfig --enable-frei0r --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libmfx --enable-libmodplug --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libwavpack --enable-libwebp --enable-libxavs --enable-libxvid --enable-libzimg --enable-libsnappy --enable-gpl --enable-opengl --enable-libcdio --enable-libfdk-aac --enable-libkvazaar --enable-librubberband --enable-libssh --enable-libtesseract --enable-libzvbi --enable-chromaprint --enable-libopenh264 --enable-libopenmpt --enable-libzmq --enable-libmysofa --enable-libflite --enable-openssl --extra-cflags=-fopenmp --extra-libs=-lgomp --extra-cflags=-DLIBTWOLAME_STATIC --extra-libs=-lstdc++ --extra-cflags=-DLIBSSH_STATIC --extra-ldflags=-Wl,--allow-multiple-definition --extra-cflags=-DCACA_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCHROMAPRINT_NODLL --extra-libs=-lstdc++ --extra-cflags=-DZMQ_STATIC --extra-libs=-lpsapi --disable-w32threads --extra-cflags=-DPTW32_STATIC_LIB --extra-libs=-lpthread --extra-libs=-lwsock32 --extra-cflags=-DKVZ_STATIC_LIB --enable-version3 --enable-nonfree --enable-filter=frei0r --disable-debug
ERROR: x265 not found using pkg-config
```

**Comment by laurfb** [comment] 2017-11-12 08:55
libx265 removed source/x265-extras.h and source/x265-extras.cpp (csv and dither functions were moved into api structure in commit 563cbe1) which seems to broke ffmpeg configure.
Temporary fix is to change line 1122 in media-suite_compile.sh to:
if [[ ! $x265 = "n" ]] && do_vcs "hg::https://bitbucket.org/multicoreware/x265#commit=bd438ce^"; then

regards,
laur

**Comment by Selur** [comment] 2017-11-12 14:12
https://bitbucket.org/multicoreware/x265/issues/371/x265-not-found-using-pkg-config might be interesting, seems like the build needs and additional  'do_addOption --extra-libs=-lpthread'

**Comment by kliffgomel** [comment] 2017-11-13 09:31
Same error..
┌ ffmpeg git ........................................ [Recently updated]
├ Changing options to comply to nonfree...
FFmpeg and related apps will depend on CUDA SDK!
FFmpeg and related apps will depend on Nvidia drivers!
├ Compiling static FFmpeg...
├ Running configure...
Likely error:
CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++ -L/local64/lib -L/mingw64/lib
../configure --prefix=/local64 --bindir=/local64/bin-video --pkg-config-flags=--static --enable-avisynth --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-cuda --enable-cuvid --enable-decklink --enable-fontconfig --enable-frei0r --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libmfx --enable-libmodplug --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libwavpack --enable-libwebp --enable-libxavs --enable-libxvid --enable-libzimg --enable-openssl --enable-libsnappy --enable-gpl --enable-opencl --enable-opengl --enable-libcdio --enable-libfdk-aac --enable-libkvazaar --enable-librubberband --enable-libssh --enable-libtesseract --enable-libzvbi --enable-chromaprint --enable-libopenh264 --enable-libopenmpt --enable-libnpp --enable-libzmq --enable-libmysofa --enable-cuda-sdk --enable-libflite --extra-cflags=-fopenmp --extra-libs=-lgomp --extra-cflags=-DLIBTWOLAME_STATIC --extra-libs=-lstdc++ --extra-cflags=-DLIBSSH_STATIC --extra-ldflags=-Wl,--allow-multiple-definition --extra-cflags=-DCACA_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCHROMAPRINT_NODLL --extra-libs=-lstdc++ --extra-cflags=-DZMQ_STATIC --extra-libs=-lpsapi --disable-w32threads --extra-cflags=-DPTW32_STATIC_LIB --extra-libs=-lpthread --extra-libs=-lwsock32 --extra-cflags=-DKVZ_STATIC_LIB --enable-version3 --enable-nonfree --extra-cflags=-IC:/PROGRA~1/NVIDIA~2/CUDA/v9.0/include --extra-ldflags=-LC:/PROGRA~1/NVIDIA~2/CUDA/v9.0/lib/x64 --enable-filter=frei0r --disable-debug
ERROR: x265 not found using pkg-config
[si_F.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/1466251/si_F.zip)

**Comment by jane1969** [comment] 2017-11-13 10:33
> Its ffmpeg related, some changes in the code made the header file a not valid c header, only a valid cpp header.
--
@GDXN has the right explanation: if you turn in x265.h all "&" into "*" in order to comply with "C" and not "C++" syntax, the issue is solved.

But once you have gone through this error (either by this correction or by changing line 1122 in media-suite_compile.sh as @laurfb suggested, ffmpeg still cannot compile. The process hangs in "running configure in ffmpeg-git", and the last line of config.log is related to "check_cflags -fdiagnostics-color=auto" of "configure" file.
I tried on two different environments (W7 and W10).

**Comment by LigH-de** [comment] 2017-11-13 10:46
A fix is being submitted to x265...

[x265.h: change references into pointers for C compatibility](https://mailman.videolan.org/pipermail/x265-devel/2017-November/011374.html)

**Comment by LigH-de** [comment] 2017-11-14 07:43
[Patch](https://bitbucket.org/multicoreware/x265/commits/533c167774e879f00c0e4e6ee247c628fb81315b) was committed.

**Comment by hydra3333** [comment] 2017-11-14 10:04
thank you.

**Comment by Metaphorce812** [comment] 2017-11-19 20:07
Not having this problem anymore. Is anyone else? If not I think this issue should be closed.

**Comment by LigH-de** [comment] 2017-11-19 21:06
Yes, the mentioned patch should have fixed it, and I was able to build most tools of the whole suite. But I am not able to close this issue.

**Closed** 2017-11-22 19:19 UTC

**Comment by Selur** [comment] 2019-03-05 16:04
getting:
> ERROR: x265 not found using pkg-config

[logs.zip](https://0x0.st/zo9F.zip)
