### ISSUE TITLE
ffmpeg can't find dcadec, suite halts

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#232] opened 2016-01-01 09:31 UTC
The media-autobuild_suite has a habit of not being able to compile several projects for the first time, but suddenly knows that it needs to install more packages next time you run it. But this time, it did not install dcadec for ffmpeg.

Console:
```
┌ ffmpeg git ............... [Updates found]
├ Running configure...
configure failed. Check /build/ffmpeg-git/ab-suite.configure.error.log
```
/build/ffmpeg-git/ab-suite.configure.error.log:

```
ERROR: dcadec not found using pkg-config

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.
```
Tail from /build/ffmpeg-git/config.log:

```
check_pkg_config dcadec >= 0.1.0 libdcadec/dca_context.h dcadec_context_create
pkg-config --exists --print-errors dcadec >= 0.1.0
Package dcadec was not found in the pkg-config search path.
Perhaps you should add the directory containing `dcadec.pc'
to the PKG_CONFIG_PATH environment variable
No package 'dcadec' found
ERROR: dcadec not found using pkg-config
```

**Comment by wiiaboo** [comment] 2016-01-01 13:38
But is dcadec compiled properly or is this just caused by #231 ?

**Comment by LigH-de** [comment] 2016-01-01 15:17
It seems to be related to the previous fix. After this, dcadec was compiled at all for the first time. Then ffmpeg passed too.

**Comment by wiiaboo** [comment] 2016-01-01 15:21
Then you can close it?

**Closed** 2016-01-01 16:23 UTC
