### ISSUE TITLE
ERROR: x265 not found using pkg-config

### ISSUE THREAD

**Issue by ConvertApple** [jb-alvarado/media-autobuild_suite#291] opened 2016-03-02 12:55 UTC
I ran the script but after running configure on ffmpeg it errored:- 
ERROR: x265 not found using pkg-config

When I run the script it gets to ffmeg configure but then errors:
ERROR: x265 not found using pkg-config
I edited the media-autobuild_suite.ini removing --enable-libx265 from ffmpeg_options and then manually running configure ran OK, but then running make still failed.

x265 seems to be building correctly so I wonder if the resultant files aren't being copied to the correct place for ffmpeg/configure to find them? I can include full logs if required, but maybe it is an obvious fix?

I also wonder why some of the libs run Uninstall then re-run configure+make when they don't appear to have changed. They do this every time the script is run. e.g: fontconfig, bin-fdk-aac, opus-tools-0.1.9 eg:- 
fontconfig 2.11.94 ........................................ [Up-to-date]
├ fontconfig-2.11.94 ................................. [File up-to-date]
├ Running uninstall...
├ Running configure...
├ Running make...
├ Running install...
└ fontconfig-2.11.94 ......................................... [Updated]

---- ffmpeg Log 
├ Compiling static FFmpeg...
├ Running configure...
Likely error:
../configure --prefix=/local64 --bindir=/local64/bin-video --pkg-config-flags=--static --disable-w32threads --enable-decklink --enable-fontconfig --enable-gcrypt --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libfribidi --enable-libkvazaar --enable-libmfx --enable-libmp3lame --enable-libopus --enable-libsoxr --enable-libspeex --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzimg --enable-libzvbi --enable-opengl --enable-avisynth --extra-cflags=-DLIBTWOLAME_STATIC --extra-cflags=-DCACA_STATIC --extra-cflags=-DKVZ_STATIC_LIB --enable-gpl --disable-debug --extra-version=g29c6fd4
ERROR: x265 not found using pkg-config

----media-autobuild_suite.ini
[compiler list]
msys2Arch=2
arch=3
license2=1
xpcomp=2
standalone=1
vpx2=1
x2642=1
x2652=1
other265=1
flac=1
fdkaac=1
mediainfo=2
soxB=1
ffmpegB=1
ffmpegUpdate=2
ffmpegChoice=2
mp4box=2
rtmpdump=2
mplayer=2
mpv=2
bmx=2
cores=4
deleteSource=2
strip=1
pack=2
logging=1

**Comment by wiiaboo** [comment] 2016-03-02 13:54
Upload logs.zip. I can't guess what's wrong.

**Comment by nille02** [comment] 2016-03-02 13:56
In the past, i see a error that a pkg patch can't be applied to ffmpeg.

**Comment by wiiaboo** [comment] 2016-03-02 13:58
"In the past" meaning before the commit that fixed it yesterday?

**Comment by nille02** [comment] 2016-03-02 14:02
[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/154901/logs.zip)

**Comment by ConvertApple** [comment] 2016-03-02 14:02
OK. I will do soon. FYI I have now created an ffmpeg.exe without x265 which is great! Unfortunately x265 hg is currently giving a down message so I'll have to wait a bit. 

I am following through your scripts to work out all the magic, so I can eventually use it to generate a patched ffmpeg from January. Your hard work is much appreciated BTW.

**Comment by nille02** [comment] 2016-03-02 14:03
My last commit is 3 days old 841eec4fbd4af363afced90b1fc36b8eab4349a7

**Comment by nille02** [comment] 2016-03-02 14:16
now it fails at mediainfo.

[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/154915/logs.zip)

Likely error:
  CXX      Help.o
  CXX      Core.o
  CXXLD    mediainfo.exe
E:/User/Desktop/compile-ffmpeg/msys64/mingw64/lib/libcurl.a(libcurl_la-openssl.o):(.text+0x654): undefined reference to `RAND_egd'
E:/User/Desktop/compile-ffmpeg/msys64/mingw64/lib/libcurl.a(libcurl_la-openssl.o):(.text+0x133a): undefined reference to `SSLv3_client_method'
E:/User/Desktop/compile-ffmpeg/msys64/mingw64/lib/libcurl.a(libcurl_la-openssl.o):(.text+0x3124): undefined reference to `SSL_CTX_set_srp_username'
E:/User/Desktop/compile-ffmpeg/msys64/mingw64/lib/libcurl.a(libcurl_la-openssl.o):(.text+0x37f9): undefined reference to `SSL_CTX_set_srp_password'
collect2.exe: error: ld returned 1 exit status
Makefile:413: recipe for target 'mediainfo.exe' failed
make: *** [mediainfo.exe] Error 1
install failed. Check /build/mediainfo-git/Project/GNU/CLI/ab-suite.install.log
This is required for other packages, so this script will exit.

**Comment by Vangelis66** [comment] 2016-03-02 15:11
@ConvertApple wrote: 

> I also wonder why some of the libs run Uninstall then re-run configure+make
> when they don't appear to have changed. They do this every time the script is run. 
> e.g: fontconfig, bin-fdk-aac, opus-tools-0.1.9 eg:- 

Please read https://github.com/jb-alvarado/media-autobuild_suite/issues/273
(as explained, that should only happen when 
the suite has not managed once to compile ffmpeg.exe)

> but after running configure on ffmpeg it errored:-
> ERROR: x265 not found using pkg-config

Your issue title is exactly the same as previous https://github.com/jb-alvarado/media-autobuild_suite/issues/280, 
which was fixed on its own...

Regards

**Comment by ConvertApple** [comment] 2016-03-02 15:16
OK Thanks for all your help. I'll try and make more progress tomorrow.

**Comment by wiiaboo** [comment] 2016-03-02 16:44
@nille02 your bug should be fixed now.

@ConvertApple I still need your logs.zip.

**Comment by wiiaboo** [comment] 2016-03-02 16:50
This was caused by x265, afaik, and it's been fixed already.

**Closed by wiiaboo** 2016-03-02 16:50 UTC
Labels: more info needed

**Comment by ConvertApple** [comment] 2016-03-02 16:53
I only downloaded the script for the first time yesterday, so unsure why I got error if it was fixed. 
x265 hg was down when I last tried so no logs yet.

**Comment by wiiaboo** [comment] 2016-03-02 17:14
It was fixed since you ran it, in https://bitbucket.org/multicoreware/x265/commits/39b9334593cfe67b24d998ade2fa1895f342afb3

**Comment by ConvertApple** [comment] 2016-03-02 20:19
Ah OK the script said it was down. I've got the latest script changes and it all now compiles perfectly. Thanks for all your help and great work in creating this tool.
