### ISSUE TITLE
Error running git update for flac

### ISSUE THREAD

**Issue by ycwan** [jb-alvarado/media-autobuild_suite#1332] opened 2019-08-06 22:39 UTC
05:38:39   Running git update for flac...
05:38:42 ┌ flac git  .................................... [Updates found]
05:38:44 ├ Running autogen...
Likely error:
libtoolize: linking file 'm4/ltversion.m4'
libtoolize: linking file 'm4/lt~obsolete.m4'
configure.ac:41: error: installing './ar-lib'; error while making link: Operation not permitted
configure.ac:39: error: installing './compile'; error while making link: Operation not permitted
configure.ac:42: error: installing './config.guess'; error while making link: Operation not permitted
configure.ac:42: error: installing './config.sub'; error while making link: Operation not permitted
configure.ac:26: error: installing './install-sh'; error while making link: Operation not permitted
configure.ac:26: error: installing './missing'; error while making link: Operation not permitted
examples/c/decode/file/Makefile.am: error: installing './depcomp'; error while making link: Operation not permitted
autoreconf: automake failed with exit status: 1
autogen failed. Check C:/mingw/build/flac-git/ab-suite.autogen.log
This is required for other packages, so this script will exit.
05:39:24   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/zOVi.zip
Copy and paste [logs.zip](https://0x0.st/zOVi.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by 1480c1** [comment] 2019-08-06 22:43
You did update right?

**Comment by wiiaboo** [comment] 2019-08-06 22:46
No. And didn't see that this is an exact duplicate of #1325 either.

**Closed by wiiaboo** 2019-08-06 22:46 UTC
