### ISSUE TITLE
[mingw64] [ffmpeg] Can't build with --enable-cuda-llvm

### ISSUE THREAD

**Issue by fuchanghao** [jb-alvarado/media-autobuild_suite#1320] opened 2019-08-05 05:57 UTC
I tried to build FFmpeg with "--enable-cuda-llvm" but it fails.

used "--enable-cross-compile" still not work.

used Custom profile not wrok.

installed WDK and spectre libs still not wrok.

commit:dfe7cb2fa15df64ce8d918654ac6b008178613e8

error:https://0x0.st/zOmb.zip

> [313m05:51:20(B[m [1m┌ ffmpeg git (B[m ............................... [[311mRecently updated(B[m]
> [313m05:51:20(B[m [1m├(B[m Changing options to comply to nonfree...
> [311mFFmpeg and related apps will depend on CUDA SDK to run!(B[m
> [311mzLsN.txt(B[m
> 	Patch couldn't be applied with 'git am'. Continuing without patching.
> [313m05:51:25(B[m [1m├(B[m Compiling [1mshared(B[m FFmpeg...
> [313m05:51:26(B[m [1m├(B[m Running configure...
> Likely error:
> gcc is unable to create an executable file.
> If gcc is a cross-compiler, use the --enable-cross-compile option.
> Only do this if you know what cross compiling means.
> C compiler test failed.
> 
> If you think configure made a mistake, make sure you are using the latest
> version from Git.  If the latest version fails, report the problem to the
> ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
> Include the log file "ffbuild/config.log" produced by configure as this will help
> solve the problem.
> [31mconfigure failed. Check C:/media-autobuild_suite/build/ffmpeg-git/build-shared-64bit/ab-suite.configure.log(B[m
> [31mThis is required for other packages, so this script will exit.(B[m
> [313m05:51:45(B[m   Creating diagnostics file...
> 
> [32mAll relevant logs have been anonymously uploaded to https://0x0.st/zOmb.zip
> [32mCopy and paste [31m[logs.zip](https://0x0.st/zOmb.zip)[32m in the GitHub issue.(B[m
> Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
> Try running the build again at a later time.

> # Lines starting with this character are ignored
> 
> # Basic built-in options, can be removed if you delete "--disable-autodetect"
> --disable-autodetect
> --enable-amf
> --enable-bzlib
> --enable-cuda
> --enable-cuvid
> --enable-d3d11va
> --enable-dxva2
> --enable-iconv
> --enable-lzma
> --enable-nvenc
> --enable-schannel
> --enable-zlib
> --enable-sdl2
> --disable-debug
> --enable-ffnvcodec
> --enable-nvdec
> 
> # Common options
> --enable-gmp
> --enable-libmp3lame
> --enable-libopus
> --enable-libvorbis
> --enable-libvpx
> --enable-libx264
> --enable-libx265
> --enable-libdav1d
> 
> # Zeranoe
> --enable-fontconfig
> --enable-gnutls
> --enable-libass
> --enable-libbluray
> --enable-libfreetype
> --enable-libmfx
> --enable-libmysofa
> --enable-libopencore-amrnb
> --enable-libopencore-amrwb
> --enable-libopenjpeg
> --enable-libsnappy
> --enable-libsoxr
> --enable-libspeex
> --enable-libtheora
> --enable-libtwolame
> --enable-libvidstab
> --enable-libvo-amrwbenc
> --enable-libwavpack
> --enable-libwebp
> --enable-libxml2
> --enable-libzimg
> --enable-libshine
> --enable-gpl
> --enable-openssl
> --enable-libtls
> --enable-avisynth
> --enable-mbedtls
> --enable-libxvid
> --enable-libaom
> --enable-libopenmpt
> --enable-version3
> 
> # Full
> --enable-chromaprint
> --enable-cuda-nvcc
> --enable-cuda-llvm
> --enable-decklink
> --enable-frei0r
> --enable-libbs2b
> --enable-libcaca
> --enable-libcdio
> --enable-libfdk-aac
> --enable-libflite
> --enable-libfribidi
> --enable-libgme
> --enable-libgsm
> --enable-libilbc
> --enable-libkvazaar
> --enable-libmodplug
> --enable-libnpp
> --enable-libopenh264
> --enable-librtmp
> --enable-librubberband
> --enable-libssh
> --enable-libtesseract
> --enable-libxavs
> --enable-libzmq
> --enable-libzvbi
> --enable-openal
> --enable-opencl
> --enable-opengl
> --enable-libvmaf
> --enable-libcodec2
> --enable-libsrt
> --enable-ladspa
> --enable-libsvthevc
> --enable-vapoursynth
> #--enable-librav1e
> #--enable-liblensfun
> 

Costom profile

> # adapt these to your environment
> _cuda_basepath="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA"
> _cuda_version=v10.1
> 
> _msvc_basepath="C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC"
> _msvc_version=14.22.27905
> _msvc_hostarch=x64
> _msvc_targetarch=x64
> 
> # you shouldn't need to change these unless your environment is weird or you know what you're doing
> export CUDA_PATH=$(cygpath -sm "${_cuda_basepath}")/${_cuda_version}
> export PATH=$PATH:$(dirname "$(cygpath -u "\\${_msvc_basepath}\\${_msvc_version}\bin\Host\\${_msvc_hostarch}\\${_msvc_targetarch}\cl.exe")")
> export PATH=$PATH:$CUDA_PATH/bin

**Comment by 1480c1** [comment] 2019-08-05 06:35
``` none
gcc -D_FORTIFY_SOURCE=2 -D__USE_MINGW_ANSI_STDIO=1 -mthreads -mtune=generic -O2 -pipe -fopenmp -DLIBTWOLAME_STATIC -DLIBSSH_STATIC -DCACA_STATIC -DMODPLUG_STATIC -DCHROMAPRINT_NODLL -DZMQ_STATIC -DLIBXML_STATIC -DKVZ_STATIC_LIB -IC:/PROGRA~1/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include -c -o /tmp/ffconf.liHCeiEU/test.o /tmp/ffconf.liHCeiEU/test.c
gcc.exe: error: GPU: No such file or directory
gcc.exe: error: Computing: No such file or directory
gcc.exe: error: Toolkit/CUDA/v10.1/include: No such file or directory
```
Your include path is messed up

**Comment by 1480c1** [comment] 2019-08-05 06:39
You probably don't need your custom profile as the suite should autodetect cuda since you have it in the default location

**Comment by fuchanghao** [comment] 2019-08-05 07:22
> 
> 
> ```
> gcc -D_FORTIFY_SOURCE=2 -D__USE_MINGW_ANSI_STDIO=1 -mthreads -mtune=generic -O2 -pipe -fopenmp -DLIBTWOLAME_STATIC -DLIBSSH_STATIC -DCACA_STATIC -DMODPLUG_STATIC -DCHROMAPRINT_NODLL -DZMQ_STATIC -DLIBXML_STATIC -DKVZ_STATIC_LIB -IC:/PROGRA~1/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include -c -o /tmp/ffconf.liHCeiEU/test.o /tmp/ffconf.liHCeiEU/test.c
> gcc.exe: error: GPU: No such file or directory
> gcc.exe: error: Computing: No such file or directory
> gcc.exe: error: Toolkit/CUDA/v10.1/include: No such file or directory
> ```
> 
> Your include path is messed up

I  deleted the custom profile.

re-install the CUDA toolkit.

Even though I disable the nvcc or libnpp or not it still not work.

error log: https://0x0.st/zOmY.zip

> [313m07:10:43(B[m [1m├(B[m [32mCompiling FFmpeg with Vapoursynth R46(B[m(B[m
> [313m07:10:43(B[m [1m├(B[m [311mFFmpeg will need vapoursynth.dll and vsscript.dll to run using vapoursynth demuxers!(B[m(B[m
> [313m07:10:45(B[m   Running git update for ffmpeg...
> [313m07:10:49(B[m [1m┌ ffmpeg git (B[m ............................... [[311mRecently updated(B[m]
> [313m07:10:49(B[m [1m├(B[m Changing options to comply to nonfree...
> [311mzLsN.txt(B[m
> 	Patch couldn't be applied with 'git am'. Continuing without patching.
> [313m07:10:54(B[m [1m├(B[m Compiling [1mshared(B[m FFmpeg...
> [313m07:10:55(B[m [1m├(B[m Running configure...
> Likely error:
> CFLAGS: -mthreads -mtune=generic -O2 -pipe
> LDFLAGS: -pipe -static-libgcc -static-libstdc++ -L/local64/lib -L/mingw64/lib
> ../configure --disable-static --enable-shared --pkg-config-flags=--static --disable-autodetect --enable-amf --enable-bzlib --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-iconv --enable-lzma --enable-nvenc --enable-zlib --enable-sdl2 --disable-debug --enable-ffnvcodec --enable-nvdec --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libdav1d --enable-fontconfig --enable-libass --enable-libbluray --enable-libfreetype --enable-libmfx --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libwavpack --enable-libwebp --enable-libxml2 --enable-libzimg --enable-libshine --enable-gpl --enable-avisynth --enable-libxvid --enable-libaom --enable-libopenmpt --enable-version3 --enable-chromaprint --enable-cuda-llvm --enable-decklink --enable-frei0r --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libfdk-aac --enable-libflite --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libkvazaar --enable-libmodplug --enable-libopenh264 --enable-librtmp --enable-librubberband --enable-libssh --enable-libtesseract --enable-libxavs --enable-libzmq --enable-libzvbi --enable-openal --enable-opencl --enable-opengl --enable-libvmaf --enable-libcodec2 --enable-libsrt --enable-ladspa --enable-libsvthevc --enable-vapoursynth --enable-openssl --extra-cflags=-fopenmp --extra-libs=-lgomp --extra-cflags=-DLIBTWOLAME_STATIC --extra-libs=-lstdc++ --extra-cflags=-DLIBSSH_STATIC --extra-ldflags=-Wl,--allow-multiple-definition --extra-cflags=-DCACA_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCHROMAPRINT_NODLL --extra-libs=-lstdc++ --extra-cflags=-DZMQ_STATIC --extra-libs=-lpsapi --extra-cflags=-DLIBXML_STATIC --extra-libs=-liconv --disable-w32threads --extra-cflags=-DKVZ_STATIC_LIB --enable-nonfree --prefix=/local64/bin-video/ffmpegSHARED
> ERROR: cuda_llvm requested but not found
> 
> If you think configure made a mistake, make sure you are using the latest
> version from Git.  If the latest version fails, report the problem to the
> ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
> Include the log file "ffbuild/config.log" produced by configure as this will help
> solve the problem.
> [31mconfigure failed. Check C:/media-autobuild_suite/build/ffmpeg-git/build-shared-64bit/ab-suite.configure.log(B[m
> [31mThis is required for other packages, so this script will exit.(B[m
> [313m07:15:01(B[m   Creating diagnostics file...
> 
> [32mAll relevant logs have been anonymously uploaded to https://0x0.st/zOmY.zip
> [32mCopy and paste [31m[logs.zip](https://0x0.st/zOmY.zip)[32m in the GitHub issue.(B[m
> Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
> Try running the build again at a later time.

**Comment by 1480c1** [comment] 2019-08-05 16:20
``` none
gcc -D_FORTIFY_SOURCE=2 -D__USE_MINGW_ANSI_STDIO=1 -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -U__STRICT_ANSI__ -D__USE_MINGW_ANSI_STDIO=1 -D__printf__=__gnu_printf__ -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -DPIC -DOPJ_STATIC -mthreads -mtune=generic -O2 -pipe -fopenmp -DLIBTWOLAME_STATIC -DLIBSSH_STATIC -DCACA_STATIC -DMODPLUG_STATIC -DCHROMAPRINT_NODLL -DZMQ_STATIC -DLIBXML_STATIC -DKVZ_STATIC_LIB -std=c11 -fomit-frame-pointer -pthread -DLIBXML_STATIC -IC:/media-autobuild_suite/local64/include/harfbuzz -IC:/media-autobuild_suite/local64/include/fribidi -IC:/media-autobuild_suite/local64/include/freetype2 -IC:/media-autobuild_suite/msys64/mingw64/include/libxml2 -DLIBXML_STATIC -IC:/media-autobuild_suite/msys64/mingw64/include/libxml2 -IC:/media-autobuild_suite/local64/include/bs2b -DLIBXML_STATIC -IC:/media-autobuild_suite/local64/include/freetype2 -IC:/media-autobuild_suite/msys64/mingw64/include/libxml2 -IC:/media-autobuild_suite/local64/include/freetype2 -IC:/media-autobuild_suite/local64/include/fribidi -IC:/media-autobuild_suite/msys64/mingw64/include/libmodplug -IC:/media-autobuild_suite/msys64/mingw64/include/openjpeg-2.3 -IC:/media-autobuild_suite/local64/include/opus -IC:/media-autobuild_suite/local64/include/opus -IC:/media-autobuild_suite/local64/include/rubberband -IC:/media-autobuild_suite/local64/include/srt -IC:/media-autobuild_suite/local64/include/svt-hevc -IC:/media-autobuild_suite/local64/include/leptonica -IC:/media-autobuild_suite/msys64/mingw64/include/libxml2 -DAL_LIBTYPE_STATIC -IC:/media-autobuild_suite/local64/include/AL -IC:/media-autobuild_suite/local64/include/vapoursynth -Wdeclaration-after-statement -Wall -Wdisabled-optimization -Wpointer-arith -Wredundant-decls -Wwrite-strings -Wtype-limits -Wundef -Wmissing-prototypes -Wno-pointer-to-int-cast -Wstrict-prototypes -Wempty-body -Wno-parentheses -Wno-switch -Wno-format-zero-length -Wno-pointer-sign -Wno-unused-const-variable -Wno-bool-operation -Wno-char-subscripts -O3 -fno-math-errno -fno-signed-zeros -fno-tree-vectorize -Werror=format-security -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=return-type -Werror=vla -Wformat -fdiagnostics-color=auto -Wmaybe-uninitialized -c -o /tmp/ffconf.kjJTfPc3/test.o /tmp/ffconf.kjJTfPc3/test.c
ERROR: cuda_llvm requested but not found
```
the error is very generic this time, maybe time to report to ffmpeg instead

**Comment by 1480c1** [comment] 2019-08-05 17:13
Theoretically, you should need to install clang for windows, the suite will install clang
https://github.com/jb-alvarado/media-autobuild_suite/blob/dfe7cb2fa15df64ce8d918654ac6b008178613e8/build/media-suite_helper.sh#L1952

**Comment by lars18th** [comment] 2019-08-05 17:39
Hi,

I post here my experience, because I want to compile ffmpeg without installing the CUDA SDK too.

- My first try to compile ffmpeg in _LINUX_ without the SDK fails. It's required to use clang 3.9 or up. Read more: https://llvm.org/docs/CompileCudaWithLLVM.html

So, which version of CLANG installs the suite? And someone has already compiled last ffmpeg with the suite and without CUDA SDK, but with cuda-llvm?

**Comment by 1480c1** [comment] 2019-08-05 17:54
The suite installs the latest from msys2 mingw-w64 repo (8.0.0 ATM)

**Comment by wiiaboo** [comment] 2019-08-05 19:49
You're either in a filesystem without support for symlinks or you have them disabled in your installation.
But the issue is with FFmpeg. Their code to check for cuda_llvm support uses $source_link instead of $source_path like everything else and doesn't add a space after `-include` so MSYS2 doesn't convert the path for clang.
I've sent a patch to ffmpeg. It should be merged quickly since it's trivial.

**Comment by wiiaboo** [comment] 2019-08-05 21:01
Fix commited upstream.

**Closed by wiiaboo** 2019-08-05 21:01 UTC

**Comment by lars18th** [comment] 2019-08-06 08:15
> Fix commited upstream.

https://github.com/FFmpeg/FFmpeg/commit/5ac28e9cc19069a104f5534dcf603218066d144c
Thank you!
