### ISSUE TITLE
request: x265 with SVT-HEVC

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#1103] opened 2019-02-21 20:51 UTC
x265 now allows to use SVT-HEVC (see: https://x265.readthedocs.io/en/latest/svthevc.html).
(no clue why they didn't make a separate project out of this)
Still it would be nice if media-autobuild_suite would also support this.

**Comment by 1480c1** [comment] 2019-02-21 21:11
I'm interested in this too.
I think it's because svt-hevc is from Intel and is a separate project. afaik, you have to build svt then enable svt in x265 by flag. I think svt-hevc might require avx or sse based on the other svt-* projects.

**Comment by wiiaboo** [comment] 2019-02-22 00:33
What's the point? Why would you not just use SVT-HEVC?

**Comment by 1480c1** [comment] 2019-02-22 00:37
Supposedly so that you can use x265 as the in between since x265 has more known options that they translate for you to svt and maybe be able to use svt-hevc with ffmpeg by passing options through --x265-parms(?)

**Comment by 1480c1** [comment] 2019-02-22 02:26
Right now, I'm having problems with librt, seems that it's a posix, thing, going to see if there is a way around it. It seems it doesn't use avx, so on that point, maybe fine?

**Comment by wiiaboo** [comment] 2019-02-22 17:38
Try to remove -march=native if possible, since that would restrict builds of this to same or newer hardware than where it is compiled. If people want it on their `custom_build_options`, that's fine, so don't remove it from the environment's CFLAGS.

**Comment by 1480c1** [comment] 2019-02-22 18:02
Will try to find a way to only run if at least sse4.1 is detected and fail if not.

<https://github.com/VcDevel/Vc/blob/master/cmake/OptimizeForArchitecture.cmake> this seems promising for at least a start.

**Comment by Selur** [comment] 2019-03-12 06:49
Any progress on this?
> What's the point? Why would you not just use SVT-HEVC?

ease of usage :) adding stv itself would be nice too :)

**Comment by 1480c1** [comment] 2019-03-12 11:42
Right now, there is the code on our side to compile, problem is that even though it compiled successfully, the produced video file using the program compiled by mingw has errors.

**Comment by 1480c1** [comment] 2019-03-12 11:44
https://github.com/jb-alvarado/media-autobuild_suite/pull/1105
Tentative code,
https://github.com/intel/SVT-HEVC/issues/118
Related issue on svt-hevc side

**Comment by Selur** [comment] 2019-03-12 11:46
bummer, but thanks for looking into it :)

**Comment by 1480c1** [comment] 2019-03-12 11:47
Right now, mingw is not officially supported and is missing a lot of code from cmake and the c files

**Comment by 1480c1** [comment] 2019-03-12 11:48
Will notify once it runs properly

**Comment by Barough** [comment] 2019-06-03 14:15
Any progress on this?

**Comment by 1480c1** [comment] 2019-06-03 14:24
SVT-HEVC side still has certain things hardcoded for MSVC. I have already submitted stuff for SVT-AV1, I could try for SVT-HEVC too

**Comment by 1480c1** [comment] 2019-06-03 16:48
Please refer to #1105 for the suite side progress

**Comment by 1480c1** [comment] 2019-06-12 16:12
Probably can be completed soon(?)

**Comment by fuchanghao** [comment] 2019-06-14 11:45
> 
> 
> Probably can be completed soon(?)

Still not work now. patch can't use in this git.

4a46ebc0245abde5e528e8fb720292ac441bac94

**Comment by 1480c1** [comment] 2019-06-14 17:08
What do you mean?

**Comment by fuchanghao** [comment] 2019-06-14 17:25
all patch said Patch couldn't be applied with 'patch'. Continuing without patching.

And finally said build fails.

**Comment by 1480c1** [comment] 2019-06-14 17:26
Hmm, will check once I can get to my computer

**Comment by BlackScreen** [comment] 2019-06-17 16:24
Hm. Not working at my end... :(

```
18:18:59   Running git clone for SVT-HEVC...
18:19:05 ┌ SVT-HEVC git ............................. [Recently updated]
18:19:05 ├ Running uninstall...
18:19:16 ├ Running cmake...
18:19:28 ├ Running build...
18:20:31 ├ Running install...
18:20:31 ├ /local64/bin-video/libSvtHevcEnc.dll .. [Not found]
18:20:32 └ SVT-HEVC-git ....................................... [Failed]

Try deleting '/build/SVT-HEVC-git' and start the script again.
If you're sure there are no dependencies <Enter> to continue building.
Close this window if you wish to stop building.
```

**Comment by 1480c1** [comment] 2019-06-17 16:27
Is there a SvtHevcEncApp in bin-video?

**Comment by 1480c1** [comment] 2019-06-17 16:32
Also, please open a new issue for problems from now on instead of appending to an existing one. It makes it easier to track the problem and fix and keeps existing issues uncluttered. Plus this is a feature request issues, not a problem issue

**Comment by wiiaboo** [comment] 2019-06-17 17:57
It's a regression from the recent change to do_cmake. `bindir` was being overriden by the last while iteration.
Fixed in b90af23f4d4e73cbc6b2e24ef3f1f39a91cab88a

**Comment by BlackScreen** [comment] 2019-06-18 06:19
> Is there a SvtHevcEncApp in bin-video?
Nope, there is none. And sorry for appending it here. I will open a new issue, as I still am encountering problems...

**Comment by Selur** [comment] 2019-06-18 14:12
not sure whether it help, I enabled STV-HEVC and for me it stops at:
```
16:08:57   Running git update for SVT-HEVC...
16:08:58 ┌ SVT-HEVC git ................................ [Files missing]
16:09:04 ├ Running cmake...
16:09:13 ├ Running build...
Likely error:
                 from ../Source/Lib/C_DEFAULT/EbSampleAdaptiveOffset_C.c:7:
I:/media-autobuild_suite/msys64/mingw32/lib/gcc/i686-w64-mingw32/9.1.0/include/emmintrin.h:143:1: error: inlining failed in call to always_inline '_mm_load_sd': target specific option mismatch
  143 | _mm_load_sd (double const *__P)
      | ^~~~~~~~~~~
In file included from ../Source/Lib/C_DEFAULT/EbSampleAdaptiveOffset_C.h:9,
                 from ../Source/Lib/C_DEFAULT/EbSampleAdaptiveOffset_C.c:7:
../Source/Lib/Codec/EbDefinitions.h:266:9: note: called from here
  266 |         _mm_store_sd((double*)(dst + i), _mm_load_sd((const double*)(src + i)));
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
build failed. Check I:/media-autobuild_suite/build/SVT-HEVC-git/build-32bit/ab-suite.build.log
This is required for other packages, so this script will exit.
16:09:16   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/ze4n.zip
Copy and paste [logs.zip](https://0x0.st/ze4n.zip) in the GitHub issue.
```

**Comment by 1480c1** [comment] 2019-06-18 17:04
Please report to https://github.com/OpenVisualCloud/SVT-HEVC/pull/206 I will check to see what is the problem

**Comment by wiiaboo** [comment] 2019-06-18 17:23
That seems like a svthevc issue in using certain intrinsics in i686, not necessarily from the cmake part.
If svthevc has x86_64 required instructions (AVX or AVX2), it makes no sense to even allow building in 32-bit.

**Comment by 1480c1** [comment] 2019-06-18 17:25
Yea, I forgot to mention that they only support 64-bit. Should've added code to disable for 32-bit

**Closed** 2019-06-25 22:38 UTC
