### ISSUE TITLE
Public keyring not found

### ISSUE THREAD

**Issue by anana93** [jb-alvarado/media-autobuild_suite#474] opened 2017-02-18 08:38 UTC
Always get this error message:

`warning: Public keyring not found; have you run 'pacman-key --init'?
error: GPGME error: Invalid crypto engine`

Tried clean install, still got the same problem...

There isn't log.zip, so I upload the build folder just 80kb
[https://www.sendspace.com/file/4v2ljg](url)

**Comment by wiiaboo** [comment] 2017-02-18 12:58
Use search before opening an issue.

Duplicate of https://github.com/jb-alvarado/media-autobuild_suite/issues/471

**Closed by wiiaboo** 2017-02-18 12:58 UTC
