### ISSUE TITLE
FriBidi download link broken

### ISSUE THREAD

**Issue by kilovar40** [jb-alvarado/media-autobuild_suite#635] opened 2017-11-19 00:46 UTC
Fribidi.org download link is broken as it is now hosted on github

[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/1485175/logs.zip)

**Comment by myfreeer** [comment] 2017-11-19 03:42
Duplicate of #634

**Comment by kliffgomel** [comment] 2017-11-20 08:57
fixed

**Closed** 2017-11-25 17:28 UTC
