### ISSUE TITLE
failed to compile curl

### ISSUE THREAD

**Issue by myfreeer** [jb-alvarado/media-autobuild_suite#454] opened 2017-01-22 13:30 UTC
```
libcurl 7.52.1 ......................................... [Not installed]
┌ curl-7.52.1 ............................................. [Downloaded]
├ Running extract...
├ Running configure...
├ Running make...
Likely error:
  CCLD     curl.exe
../lib/.libs/libcurl.a(libcurl_la-openssl.o):openssl.c:(.text+0x591): undefined reference to `RAND_egd'
../lib/.libs/libcurl.a(libcurl_la-openssl.o):openssl.c:(.text+0x371b): undefined reference to `SSL_CTX_set_srp_username'
../lib/.libs/libcurl.a(libcurl_la-openssl.o):openssl.c:(.text+0x3748): undefined reference to `SSL_CTX_set_srp_password'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [Makefile:776: curl.exe] Error 1
make[2]: Leaving directory '/build/curl-7.52.1/build-64bit/src'
make[1]: *** [Makefile:658: all] Error 2
make[1]: Leaving directory '/build/curl-7.52.1/build-64bit/src'
make: *** [Makefile:894: all-recursive] Error 1
```

full logs: [logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/721953/logs.zip)

**Comment by wiiaboo** [comment] 2017-01-22 14:11
Can't reproduce. Remove libssl.a and libcurl.a from /local64/lib to force a rebuild.

From  looking at your compile.log there are a whole lot of strange errors.

**Comment by myfreeer** [comment] 2017-01-22 15:28
succeed with libcurl but fails making angleproject
```
Installing luajit-git... done
  Running git update for angleproject...
┌ angleproject git ..................................... [Files missing]
├ Running stable-checkout...
├ Running uninstall...
├ Running configure...
├ Running commit_id...
├ Running make...
Likely error:
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/libANGLE/renderer/d3d/d3d11/renderer11_utils.cpp:855:50: error: could not convert '{{<expression error>, <expresion error>, <expression error>}}' from '<brace-enclosed initializer list>' to 'std::array<unsigned int, 3ull>'
                      D3D11_CS_THREAD_GROUP_MAX_Z}};
                                                  ^
../src/libANGLE/renderer/d3d/d3d11/renderer11_utils.cpp: In function 'size_t rx::d3d11_gl::{anonymous}::GetMaxComputeWokGroupInvocations(D3D_FEATURE_LEVEL)':
../src/libANGLE/renderer/d3d/d3d11/renderer11_utils.cpp:868:20: error: 'D3D11_CS_THREAD_GROUP_MAX_THREADS_PER_GROUP' wa not declared in this scope
             return D3D11_CS_THREAD_GROUP_MAX_THREADS_PER_GROUP;
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [src/libANGLE.target.mk:349: out/Release/obj.target/libANGLE/src/libANGLE/renderer/d3d/d3d11/renderer11_utilso] Error 1
make: Leaving directory '/build/angleproject-git/generated'
```
full logs: [logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/722028/logs.zip)

**Comment by wiiaboo** [comment] 2017-01-22 17:27
Fixed in latest commit.

**Closed by wiiaboo** 2017-01-22 17:27 UTC
