### ISSUE TITLE
ffms2: configure fails at checking FFmpeg

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#685] opened 2017-12-30 22:34 UTC
"FFmpeg light build" gets built and installed, but ffms2 test fails: `checking whether FFmpeg works... no`

[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/1594832/logs.zip)

**Comment by pat357** [comment] 2018-01-01 18:06
Your problem is related to your OPUS build: see below.
Was your opus updated at the same time ?
Did it work before ?

You could try one of the following:
(if the first doesn't work, go to next line)
- delete opus.a and all opus related dirs in build and rebuild the suite
- disable opus in ffmpeg-light
- go back to a previous opus (adapting vcs line with for example #tag=.. )

I have the feeling that rebuilding everything opus-related will give you a clean bill.
Let me know if it works !
```
-lavformat -lm -lbz2 -lz -lavcodec -liconv -lm -llzma -lz -lole32 -luser32 -ldl -lswscale -lm -lavutil -lm -luser32 -ladvapi32 -ldl >&5
H:/development/media-autobuild_suite-master/local32/opt/lightffmpeg/lib/libavcodec.a(opus.o):opus.c:(.text+0xdc6): undefined reference to `ff_opus_rc_enc_cdf'
H:/development/media-autobuild_suite-master/local32/opt/lightffmpeg/lib/libavcodec.a(opus.o):opus.c:(.text+0xf53): undefined reference to `ff_opus_rc_enc_log'
H:/development/media-autobuild_suite-master/local32/opt/lightffmpeg/lib/libavcodec.a(opus.o):opus.c:(.text+0x1135): undefined reference to `ff_opus_rc_dec_log'
H:/development/media-autobuild_suite-master/local32/opt/lightffmpeg/lib/libavcodec.a(opus.o):opus.c:(.text+0x1218): undefined reference to `ff_opus_rc_dec_cdf'
H:/development/media-autobuild_suite-master/local32/opt/lightffmpeg/lib/libavcodec.a(opus.o):opus.c:(.text+0x18f2): undefined reference to `ff_opus_rc_enc_log'
H:/development/media-autobuild_suite-master/local32/opt/lightffmpeg/lib/libavcodec.a(opus.o):opus.c:(.text+0x1ce7): undefined reference to `ff_opus_rc_dec_log'
H:/development/media-autobuild_suite-master/local32/opt/lightffmpeg/lib/libavcodec.a(opus.o):opus.c:(.text+0x1d72): undefined reference to `ff_opus_rc_dec_uint'
H:/development/media-autobuild_suite-master/local32/opt/lightffmpeg/lib/libavcodec.a(opus.o):opus.c:(.text+0x1de0): undefined reference to `ff_opus_rc_enc_log'
H:/development/media-autobuild_suite-master/local32/opt/lightffmpeg/lib/libavcodec.a(opus.o):opus.c:(.text+0x1f3a): undefined reference to `ff_opus_rc_enc_cdf'
H:/development/media-autobuild_suite-master/local32/opt/lightffmpeg/lib/libavcodec.a(opus.o):opus.c:(.text+0x1f56): undefined reference to `ff_opus_rc_dec_cdf'
H:/development/media-autobuild_suite-master/local32/opt/lightffmpeg/lib/libavcodec.a(opus.o):opus.c:(.text+0x21be): undefined reference to `ff_opus_rc_enc_uint'
H:/development/media-autobuild_suite-master/local32/opt/lightffmpeg/lib/libavcodec.a(opus.o):opus.c:(.text+0x2219): undefined reference to `ff_opus_rc_dec_log'
collect2.exe: error: ld returned 1 exit status
configure:16335: $? = 1
configure: failed program was: 
```

**Comment by pat357** [comment] 2018-01-01 18:24
I just took another look at the media-suite-compile.sh:
There shouldn't be any external codecs in this FFmpeg light build !
Did you maybe configure --enable-opus or something like that ?
Remove this in your ffmpeg configuration and just rebuild.

**Comment by LigH-de** [comment] 2018-01-01 18:31
I did not change any parameters for the ffms2 related light build. For the final ffmpeg build later in the script, I use a customized **ffmpeg_options.txt** but I would assume that the light build should not depend on it.

opus-file was installed recently.

I will delete every opus related component and try again...

**Comment by wiiaboo** [comment] 2018-01-01 18:54
It has nothing to do with libopus. FFmpeg comes with native opus encoder and decoder too. Which should be both disabled with lightffmpeg, so it's weird. Try opening a FFmpeg trac issue about it. But try forcing a recompile of lightffmpeg before.

**Comment by LigH-de** [comment] 2018-01-01 19:09
In your light build, opus is among the "disabled decoders", but still enabled in the parsers.

**Comment by LigH-de** [comment] 2018-01-01 19:31
I deleted too much...

Building opus-tools now fails with the notorious BIO_meth OpenSSL issues.

**Comment by wiiaboo** [comment] 2018-01-01 19:58
No, I just fixed that issue poorly.

This ffms2 one is caused by FFmpeg upstream, though, and it should be fixed soon.

**Closed** 2018-01-01 19:58 UTC
