### ISSUE TITLE
Error trying to compile ffmpeg

### ISSUE THREAD

**Issue by vpontin** [jb-alvarado/media-autobuild_suite#621] opened 2017-10-31 19:56 UTC
[logs.zip](https://0x0.st/ssJ0.zip)

I'm running in Windows 10 Fall Creators Update x64.

**Comment by wiiaboo** [comment] 2017-11-01 00:32
Duplicate of https://github.com/jb-alvarado/media-autobuild_suite/issues/620

**Closed by wiiaboo** 2017-11-01 00:32 UTC
