### ISSUE TITLE
Error-running make ffms2 git

### ISSUE THREAD

**Issue by ycwan** [jb-alvarado/media-autobuild_suite#646] opened 2017-12-01 05:58 UTC
┌ ffms2 git ......................................... [Recently updated]
├ Running autoreconf...
├ Running configure...
├ Running make...
Likely error:
     std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t> Conversion;
                                                            ^~~~~~~
../src/index/ffmsindex.cpp:244:28: error: 'Conversion' was not declared in this scope
         StringStorage[i] = Conversion.to_bytes(_argv[i]);
                            ^~~~~~~~~~
../src/index/ffmsindex.cpp:244:28: note: suggested alternative: '_environ'
         StringStorage[i] = Conversion.to_bytes(_argv[i]);
                            ^~~~~~~~~~
                            _environ
make: *** [Makefile:659: src/index/ffmsindex.o] Error 1
make failed. Check C:/mingw/build/ffms2-git/build-32bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/solP.zip
Copy and paste [logs.zip](https://0x0.st/solP.zip) in the GitHub issue.

**Comment by TheGreatMcPain** [comment] 2017-12-01 22:37
This a bug on ffms2's end that has to do with 'codecvt' being recently deprecated from GCC.

https://github.com/FFMS/ffms2/issues/304

**Comment by BlohoJo** [comment] 2017-12-14 14:17
I'm now being blocked by this problem.

Is there a workaround?

[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/1559484/logs.zip)

**Comment by BlohoJo** [comment] 2017-12-14 14:53
According to the issue referenced by TheGreatMcPain (FFMS/ffms2#304), the fix is to edit ..build\ffms2-git\src\index\ffmsindex.cpp and add under line 24:

`25  #include <locale>`

However, when I do that and re-run media-autobuild_suite.bat, it looks like it just re-downloads and overwrites ffmsindex.cpp with the one that errors out.

Is there a way around that?

[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/1559645/logs.zip)

**Comment by wiiaboo** [comment] 2017-12-14 19:47
Yeah, you're supposed to send a pull request to the upstream repository or
apply the patch in the building script.

**Comment by BlohoJo** [comment] 2017-12-15 03:05
> or apply the patch in the building script.

How do I do that? :P

**Comment by BlohoJo** [comment] 2017-12-15 07:53
I did try to figure it out but the last time I worked with compilers was back in circa 2000 with Mame. I am an old git. :/

**Comment by BlohoJo** [comment] 2017-12-17 15:03
The problem is still being worked on... contributor qyot27 solved it and it's [on his fork](https://github.com/qyot27/ffms2/commit/921e1295f84fe0adf1b50e7183adee96a69d9a7b). Any way to get media-autobuild_suite to use it instead of the main?

**Comment by wiiaboo** [comment] 2017-12-17 16:48
Ideally, the fork should PR the fix. I shouldn't have to know whose fork fixes what for how long.

**Comment by qyot27** [comment] 2017-12-17 18:17
What was fixed on my personal triage branch wasn't FFMS2 `master`.  It was/[would be](https://github.com/FFMS/ffms2/pull/307) the `c_plugin` branch, which stays separate from `master` because it doesn't use autotools.  `master` would still need that Makefile.am patch @jtanx posted in https://github.com/FFMS/ffms2/issues/304.

**Closed** 2017-12-20 02:46 UTC
