### ISSUE TITLE
sox build fail with sndfile build

### ISSUE THREAD

**Issue by kilovar40** [jb-alvarado/media-autobuild_suite#638] opened 2017-11-19 21:27 UTC
[logs.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/1486002/logs.zip)

  Running git update for sndfile...
┌ sndfile git .......................................... [Files missing]
├ Running autogen...
Likely error:
checking for autogen ...
You must have GNU autogen installed to compile libsndfile.
Download the appropriate package for your distribution,
or get the source tarball at ftp://ftp.gnu.org/pub/gnu/
no
checking for autoconf ... yes
checking for automake ... yes
checking for libtool ... libtoolize
checking for pkg-config ... yes
checking for python ... yes
autogen failed. Check C:/Users/admin/Downloads/media-autobuild_suite/build/sndfi                le-git/ab-suite.autogen.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/s-1N.zip
Copy and paste [logs.zip](https://0x0.st/s-1N.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fi                xed already.
Try running the build again at a later time.

**Comment by kliffgomel** [comment] 2017-11-21 14:27
At me such problem does not arise.

**Comment by Sparktank** [comment] 2017-11-21 21:54
Same error when it gets to building audio tools.
Building 64bit only using the non-distributable options.

  Running git update for sndfile...
┌ sndfile git ....................................... [Recently updated]
├ Running autogen...
Likely error:
checking for autogen ...
You must have GNU autogen installed to compile libsndfile.
Download the appropriate package for your distribution,
or get the source tarball at ftp://ftp.gnu.org/pub/gnu/
no
checking for autoconf ... yes
checking for automake ... yes
checking for libtool ... libtoolize
checking for pkg-config ... yes
checking for python ... yes
autogen failed. Check C:/MAS/build/sndfile-git/ab-suite.autogen.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/s-t6.zip
Copy and paste [logs.zip](https://0x0.st/s-t6.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.


**ab-suite.autogen.log**
CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
./autogen.sh 
checking for autogen ... 
You must have GNU autogen installed to compile libsndfile.
Download the appropriate package for your distribution,
or get the source tarball at ftp://ftp.gnu.org/pub/gnu/
no
checking for autoconf ... yes
checking for automake ... yes
checking for libtool ... libtoolize
checking for pkg-config ... yes
checking for python ... yes

**Comment by pat357** [comment] 2017-11-22 19:29
I'm having the same issue: exactly the same output and error.

**Comment by wiiaboo** [comment] 2017-11-25 17:29
Duplicate of https://github.com/jb-alvarado/media-autobuild_suite/issues/639

**Closed by wiiaboo** 2017-11-25 17:29 UTC
