### ISSUE TITLE
Vulkan fails to compile : patch could not be applied

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#862] opened 2018-06-15 19:20 UTC
Maybe we need a new patch for vulkan  ? Or use the new repo's instead of the older one.

I took a look at the repo and it says it's **depreciated**, see below:
```
@@ -1,3 +1,23 @@
+# Vulkan-LoaderAndValidationLayers Has Been Deprecated
+
+This repository has been deprecated. It will continue to exist as a read-only repository servicing existing projects. Any
+projects utilizing this repository should be migrated to use the follow-on repositories listed below. All issues have been migrated to the
+new repositories.
+
+The four new repositories are:
+
+- [Vulkan-Headers](https://github.com/KhronosGroup/Vulkan-Headers)
+- [Vulkan-Loader](https://github.com/KhronosGroup/Vulkan-Loader)
+- [Vulkan-ValidationLayers](https://github.com/KhronosGroup/Vulkan-ValidationLayers)
+- [Vulkan-Tools](https://github.com/KhronosGroup/Vulkan-Tools)
+
+Repository Maintainers,
+    May 13, 2018
+
+Contact: mark@lunarg.com 
```
The current patch for **vulcan from Shinchiro** **is made for the new repo's , not for the depreciated one.
I see Shinchiro uses https://github.com/KhronosGroup/Vulkan-Headers and https://github.com/KhronosGroup/Vulkan-Loader.git** 

The reason for patch can not be applied is that we use a **new patch made for the new repo's** and try to apply this patch **on the depreciated repo.**

```
  Running git clone for vulkan in .
+ [[ git = \s\v\n ]]
+ git clone https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers.git vulkan-git
Cloning into 'vulkan-git'...
remote: Counting objects: 64657, done.
remote: Total 64657 (delta 0), reused 0 (delta 0), pack-reused 64657
Receiving objects: 100% (64657/64657), 79.89 MiB | 2.36 MiB/s, done.
Resolving deltas: 100% (49631/49631), done.
+ set +x
+ [[ git = svn ]]
+ [[ git = hg ]]
+ [[ git = git ]]
+ git remote set-url origin https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers.git
+ git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
+ [[ -f .git/refs/heads/ab-suite ]]
+ git branch -f --no-track ab-suite
+ git checkout ab-suite
Switched to branch 'ab-suite'
++ vcs_getlatesttag origin/HEAD
++ local ref=origin/HEAD
++ [[ -n git ]]
++ [[ git != git ]]
++ local tag
++ [[ origin/HEAD = \L\A\T\E\S\T ]]
++ [[ origin/HEAD = \G\R\E\A\T\E\S\T ]]
++ [[ origin/HEAD != \o\r\i\g\i\n\/\H\E\A\D ]]
++ echo origin/HEAD
+ git reset --hard origin/HEAD
HEAD is now at 25d58847 docs: Update readme to reflect repo deprecation
++ git rev-parse HEAD
+ oldHead=25d5884746a2de7b51a8ef3ec88e1cd8066460e8
+ set +x
┌ vulkan git ........................................ [Recently updated]
vulkan-0001-cross-compile-static-linking-hacks.patch
        Patch couldn't be applied with 'patch'. Continuing without patching.
Running cmake in vulkan-git
```

The given error is:

```
[7/20] Linking C executable loader\asm_offset.exe
FAILED: loader/asm_offset.exe
cmd.exe /C "cd . && R:\Mingw647\msys64\mingw32\bin\gcc.exe  -m32 -mthreads -mtune=generic -O2 -pipe -D_WIN32_WINNT=0x0600 -D__STDC_FORMAT_MACROS -std=c99 -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fno-builtin-memcmp -Wimplicit-fallthrough=0 -fvisibility=hidden -D_CRT_SECURE_NO_WARNINGS -O3 -DNDEBUG  -pipe -static-libgcc -static-libstdc++ /guard:cf loader/CMakeFiles/asm_offset.dir/asm_offset.c.o  -o loader\asm_offset.exe -Wl,--major-image-version,0,--minor-image-version,0  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
gcc.exe: error: /guard:cf: No such file or directory
ninja: build stopped: subcommand failed.
This is required for other packages, so this script will exit.
  Creating diagnostics file in vulkan-git

All relevant logs have been anonymously uploaded to https://0x0.st/sLe2.zip
Copy and paste [logs.zip](https://0x0.st/sLe2.zip) in the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.

**Comment by wiiaboo** [comment] 2018-06-16 01:55
Duplicate of https://github.com/jb-alvarado/media-autobuild_suite/issues/860

**Closed by wiiaboo** 2018-06-16 01:55 UTC
