### ISSUE TITLE
rav1e support (AV1 encoding)

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#915] opened 2018-09-12 04:29 UTC
Would be nice if rav1e (https://github.com/xiph/rav1e) could be added as alternative AV1 encoder to aomenc.

Thanks!

**Comment by wiiaboo** [comment] 2018-09-12 08:12
Last time I tried it didn't work. When I have time I'll look into it, since there's already ripgrep using rust successfully.

**Comment by wiiaboo** [comment] 2018-09-12 23:12
Though rav1e is not really a complete alternative to aomenc, since it's just the standalone encoder, not a lib usable in FFmpeg, it seems to compile fine now.

**Comment by wiiaboo** [comment] 2018-09-12 23:34
If you have 32-bit and/or 64-bit mingw (not 32-bit msys2, I really don't care about that), test if compilation is working for both.

**Comment by LigH-de** [comment] 2018-09-13 11:35
Although `standalone=1` and `rav1e=1` are set in the **media-autobuild_suite.ini**, neither `rust` nor `rav1e` are mentioned anywhere in the **compile.log** and have no subdirectory under **build**. Neither **bin-global/rg.exe** nor **bin-video/rav1e.exe** exist when the suite finishes.

Tested twice.

I believe you forgot to set `$rav1e` and `$ripgrep` in the beginning of **media-suite_compile.sh**.

**Comment by LigH-de** [comment] 2018-09-13 12:33
OK, seems to help. May post a patch if you don't.

But ... rust doesn't install: [logs.zip](https://0x0.st/swGl.zip)

**ripgrep-git/ab-suite.install_rust.log**:
```
CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
bash -c curl https://sh.rustup.rs -sSf | sh -s -- -v -y --no-modify-path --default-host=i686-pc-windows-gnu --default-toolchain=stable
info: downloading installer
rustup: Unable to run interactively. Run with -y to accept defaults, --help for additional options
```

**Comment by Selur** [comment] 2018-09-13 15:47
same build problem occurs where when just rav1e is marked to be build:
 [logs.zip](https://0x0.st/swkI.zip)

**Comment by LigH-de** [comment] 2018-09-13 16:04
Yes, because the issue is in the rust installation step.

**Comment by schmidthubert** [comment] 2018-09-13 23:11
This needs fixing of the helper, subshell in a shell problem plus $CARCH should be $MSYSTEM_CARCH, I used that ... Then it needs to take care of the target bitness or add /cargo/bin path/to $PATH etc, several ways possible here, will leave it to Ricardo... I have it working already, but sorry short night and long day ahead so I can't continue now. Takes a lot of time though on first run, puts over 2GB! in each local32 and local64 dirs BTW, so be prepared. But the good thing is this can be fixed ... :+1: 
![png](https://user-images.githubusercontent.com/26191502/45520610-64ef3b00-b7ba-11e8-87c3-178fe7894af8.PNG)

**Comment by schmidthubert** [comment] 2018-09-14 00:05
https://github.com/jb-alvarado/media-autobuild_suite/pull/919 should resolve it

**Comment by wiiaboo** [comment] 2018-09-14 00:08
> This needs fixing of the helper, subshell in a shell problem

Done already in 1deafc0.

> add /cargo/bin path/to $PATH etc,

Hm? That's dealt with already.

**Comment by schmidthubert** [comment] 2018-09-14 00:09
No, other variable, check PR.

**Comment by wiiaboo** [comment] 2018-09-14 00:11
What other variable? I only see you changing CARCH to MSYSTEM_CARCH, which makes sense, since it's the host.

**Comment by wiiaboo** [comment] 2018-09-14 00:11
PATH was added in https://github.com/jb-alvarado/media-autobuild_suite/commit/4874e76551c985b2db3e7e6fba02db4173270d5f#diff-996d712957fc52b29e0a57d87c1f9b50R1529

**Comment by schmidthubert** [comment] 2018-09-14 00:14
Yes, that's the variable I changed. My change was much simpler BTW:

`log install_rust bash -c 'curl https://sh.rustup.rs -sSf | sh -s -- -v -y --no-modify-path --default-host='$MSYSTEM_CARCH'-pc-windows-gnu --default-toolchain stable'`

but meanwhile you changed the helper and since GH doesn't notify anyone about such changes ... :-(

**Comment by wiiaboo** [comment] 2018-09-14 00:15
I forgot to push it.

**Comment by schmidthubert** [comment] 2018-09-14 00:40
All good now, thanks! :+1: 

![png](https://user-images.githubusercontent.com/26191502/45523095-93bfde00-b7c7-11e8-905f-1bd19683f979.PNG)

**Comment by LigH-de** [comment] 2018-09-14 09:31
Builds well with a common rust installation now.

The only cosmetical detail left to wonder: Why rav1e is located in the group of global tools instead of video tools...

Ready to close?

**Comment by LigH-de** [comment] 2018-09-14 11:05
... maybe not yet; updating an existing installation is unstable. After the installation, the 2nd run complained about being unable to remove a setup file (Windows filesystem error 5), the 3rd run complained about a directory in /opt for rust which was not found. The 4th run passed.

**Comment by wiiaboo** [comment] 2018-09-14 19:28
Should be mostly fixed by 9b3a840.

**Closed by wiiaboo** 2018-09-14 19:28 UTC

**Comment by LigH-de** [comment] 2018-09-29 05:57
Are there reasons not to move the compilation of rav1e into the group of video encoders, close to aomenc?

**Comment by wiiaboo** [comment] 2018-09-29 11:45
It's not used by anything, so just cosmetic reasons?
