### ISSUE TITLE
Can not upgrade MingW GCC

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#393] opened 2016-09-21 20:34 UTC
Is this message normal when the system is trying to update GCC ?
Do we need the -force  switch ?

```
Updating pacman database...
-------------------------------------------------------------------------------
:: Synchronizing package databases...
 mingw32 is up to date
 mingw64 is up to date
 msys is up to date
-------------------------------------------------------------------------------
Checking pacman packages...
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Checking profiles...
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
Updating msys2 system and installed packages...
-------------------------------------------------------------------------------
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: mingw-w64-i686-gcc-ada: installing mingw-w64-i686-gcc (6.2.0-1) breaks dependency 'mingw-w64-i686-gcc=6.1.0-1'
:: mingw-w64-i686-gcc-fortran: installing mingw-w64-i686-gcc (6.2.0-1) breaks dependency 'mingw-w64-i686-gcc=6.1.0-1'
:: mingw-w64-i686-gcc-libgfortran: installing mingw-w64-i686-gcc-libs (6.2.0-1) breaks dependency 'mingw-w64-i686-gcc-libs=6.1.0-1'
:: mingw-w64-i686-gcc-objc: installing mingw-w64-i686-gcc (6.2.0-1) breaks dependency 'mingw-w64-i686-gcc=6.1.0-1'
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: mingw-w64-i686-gcc-objc: installing mingw-w64-i686-gcc (6.2.0-1) breaks dependency 'mingw-w64-i686-gcc=6.1.0-1'
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: mingw-w64-i686-gcc-ada: installing mingw-w64-i686-gcc (6.2.0-1) breaks dependency 'mingw-w64-i686-gcc=6.1.0-1'
:: mingw-w64-i686-gcc-fortran: installing mingw-w64-i686-gcc (6.2.0-1) breaks dependency 'mingw-w64-i686-gcc=6.1.0-1'
:: mingw-w64-i686-gcc-libgfortran: installing mingw-w64-i686-gcc-libs (6.2.0-1) breaks dependency 'mingw-w64-i686-gcc-libs=6.1.0-1'
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: mingw-w64-x86_64-gcc-objc: installing mingw-w64-x86_64-gcc (6.2.0-1) breaks dependency 'mingw-w64-x86_64-gcc=6.1.0-1'
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: mingw-w64-x86_64-gcc-ada: installing mingw-w64-x86_64-gcc (6.2.0-1) breaks dependency 'mingw-w64-x86_64-gcc=6.1.0-1'
:: mingw-w64-x86_64-gcc-fortran: installing mingw-w64-x86_64-gcc (6.2.0-1) breaks dependency 'mingw-w64-x86_64-gcc=6.1.0-1'
:: mingw-w64-x86_64-gcc-fortran: installing mingw-w64-x86_64-gcc-libgfortran (6.2.0-1) breaks dependency 'mingw-w64-x86_64-gcc-libgfortran=6.1.0-1'
-------------------------------------------------------------------------------
Updates finished.
-------------------------------------------------------------------------------

**Comment by wiiaboo** [comment] 2016-09-21 21:11
I didn't have any issue. Are you on Win7?

**Comment by LigH-de** [comment] 2016-09-22 12:40
Similar issue here, Windows 7 SP1 x64 German:

´´´

-------------------------------------------------------------------------------
Updating pacman database...
-------------------------------------------------------------------------------

:: Synchronizing package databases...
 mingw32 is up to date
 mingw64 is up to date
 msys is up to date

-------------------------------------------------------------------------------
Checking pacman packages...
-------------------------------------------------------------------------------

-------------------------------------------------------------------------------
Checking profiles...
-------------------------------------------------------------------------------

/local32 profile up-to-date!
/local64 profile up-to-date!
-------------------------------------------------------------------------------
Updating msys2 system and installed packages...
-------------------------------------------------------------------------------
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: mingw-w64-i686-gcc-libgfortran: installing mingw-w64-i686-gcc-libs (6.2.0-1) breaks dependency 'mingw-w64-i686-gcc-libs=6.1.0-1'
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: mingw-w64-i686-gcc: installing mingw-w64-i686-gcc-libs (6.2.0-1) breaks dependency 'mingw-w64-i686-gcc-libs=6.1.0-1'
-------------------------------------------------------------------------------
Updates finished.
-------------------------------------------------------------------------------
´´´

**Comment by pat357** [comment] 2016-09-22 13:42
I'm also on Win7 SP1 x64 English

**Comment by wiiaboo** [comment] 2016-09-22 13:58
The issue is because libgfortran has a circular dependency with gcc-libs and gcc and the media-suite_update.sh staggers packages because of an issue that only happens with Win7.
Run `pacman -Su` on your own.

**Closed by wiiaboo** 2016-09-22 13:58 UTC
