### ISSUE TITLE
FFmpeg (v7) fails to build / libbluray?

### ISSUE THREAD

**Issue by Barough** [jb-alvarado/media-autobuild_suite#2630] opened 2024-04-05 19:56 UTC
Have tried with deleting the ffmpeg & libbluray folders but it haven't helped

┌ ffmpeg git  ......................................... [Recently updated]
├ Changing options to comply to nonfree...
├ Compiling static FFmpeg...
├ Running configure...
├ Running make...
Likely error (tail of the failed operation logfile):
LD      ffprobe_g.exe
D:/MABS-ffmpeg/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/13.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/MABS-ffmpeg/local32/lib/libbluray.a(libbluray_la-dec.o):dec.c:(.text+0x2e0): multiple definition of `dec_init'; fftools/ffmpeg_dec.o:ffmpeg_dec.c:(.text+0x2e00): first defined here
STRIP   ffprobe.exe
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:136: ffmpeg_g.exe] Error 1
make: *** Waiting for unfinished jobs....
LD      ffmpeg_g.exe
D:/MABS-ffmpeg/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/13.2.0/../../../../i686-w64-mingw32/bin/ld.exe: D:/MABS-ffmpeg/local32/lib/libbluray.a(libbluray_la-dec.o):dec.c:(.text+0x2e0): multiple definition of `dec_init'; fftools/ffmpeg_dec.o:ffmpeg_dec.c:(.text+0x2e00): first defined here
collect2.exe: error: ld returned 1 exit status
make: *** [/build/ffmpeg-git/Makefile:136: ffmpeg_g.exe] Error 1
make failed. Check D:/MABS-ffmpeg/build/ffmpeg-git/build-static-32bit/ab-suite.make.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/14889999/logs.zip)

**Comment by Biswa96** [comment] 2024-04-05 19:58
Duplicate of #2627

**Closed as not planned** 2024-04-30 18:03 UTC
