### ISSUE TITLE
Cannot setup a MinGW/GCC environment 32bit

### ISSUE THREAD

**Issue by laurfb** [jb-alvarado/media-autobuild_suite#166] opened 2015-09-17 05:54 UTC
The script is stopping allways with error message: "MinGW32 GCC compiler isn't installed.... Do you want to try it again?"
Doesn't matter what option is selelected, either "y" or "n", the script window is clossing with no warning.
The last line in base.log is allways "/usr/bin/bash: D:\ffmpeg_build\media-autobuild_suite-master\build\pacman.sh: No such file or directory" and in mingw32.log file "/usr/bin/bash: D:\media-autobuild_suite-master\build\mingw32.sh: No such file or directory"
The script is running on Win7 32bit and the ini file is:

[compiler list]
msys2Arch=1
arch=2
free=1
vpx=2
x264=2
x265=6
other265=2
flac=1
mediainfo=2
soxB=2
ffmpegB=1
ffmpegUpdate=1
ffmpegChoice=1
mp4box=2
mplayer=2
mpv=2
cores=2
deleteSource=1
strip=1
pack=2

best regards,
laur

**Comment by jb-alvarado** [comment] 2015-09-17 07:06
Hi laur, can you confirm that the base msys2 system is installed, or is this also missing?

**Comment by laurfb** [comment] 2015-09-17 07:17
Yes, msys2 is installed.

**Comment by jb-alvarado** [comment] 2015-09-17 08:13
Ok I can reproduce the problem to.

**Comment by jb-alvarado** [comment] 2015-09-17 09:17
The batch script runs truth the process and don't stop on installing the msys2 base packages. The files pacman.sh gets delete before it gets called. That is the only thing what I know at the moment. I am on work, so I have not much time to fix that.

**Comment by wiiaboo** [comment] 2015-09-17 11:46
There's a new September build of the msys2 base. Could be related to that.

**Comment by jb-alvarado** [comment] 2015-09-17 12:09
You think? Because this is happen with all sh scripts what get call from batch. Maybe we can change the part to: `%instdir%\%msys2%\usr\bin\bash --login %instdir%\build\*`, and only the compiler script starts from mintty?

**Comment by wiiaboo** [comment] 2015-09-17 12:25
I added --log to all:
http://j.fsbn.eu/firstrun.log
http://j.fsbn.eu/firstupdate.log
http://j.fsbn.eu/secondupdate.log

**Comment by wiiaboo** [comment] 2015-09-17 12:34
The problem is that the .bat isn't waiting for mintty to be finished like it did before.

**Comment by jb-alvarado** [comment] 2015-09-17 12:50
Yes I know. When we only call mintty at the end, and all other shell scripts with bash, it works.

**Comment by jb-alvarado** [comment] 2015-09-17 13:31
I post on the mintty issue list:
https://github.com/mintty/mintty/issues/479

**Comment by wiiaboo** [comment] 2015-09-17 13:31
The fix worked, i'm doing commits now.

**Comment by jb-alvarado** [comment] 2015-09-17 13:33
Ah, ok - nice!

**Comment by wiiaboo** [comment] 2015-09-17 13:48
Should be fixed with 6864fd37987e77a7158ea9059e696f5a8fe8361a

**Closed by wiiaboo** 2015-09-17 13:48 UTC

**Comment by jb-alvarado** [comment] 2015-09-17 15:19
I get already answer - the new mintty is now "detaching itself from the caller". This can be disable by `-d`

**Comment by wiiaboo** [comment] 2015-09-17 16:41
That's not in mintty's --help but I'll try.

**Comment by jb-alvarado** [comment] 2015-09-17 17:37
Ok, but maybe we let the other commands like they are, with bash. It is a bit more clean. What do you think?

**Comment by wiiaboo** [comment] 2015-09-17 17:52
It's "cleaner" but not loggable. IMHO anything in cmd.exe is horrible, visually.

**Comment by jb-alvarado** [comment] 2015-09-17 17:53
Hehe, that is true!

**Comment by wiiaboo** [comment] 2015-09-17 17:55
We could later hide everything at least in those temporary scripts if it can be loggable and just not show anything to the user. That way we could still use just cmd.exe but not have it be impossible to copy if problems arise.

**Comment by jb-alvarado** [comment] 2015-09-17 17:56
Yes I have also try to found a way to log and output to the screen. There is no native easy way for that. Then is better to use mintty again.

**Comment by wiiaboo** [comment] 2015-09-17 18:03
Both `bash.exe stuff.sh > stuff.log 2> stuff.error.log` and `bash.exe stuff.sh > stuff.log 2>&1` seem to work as expected.

**Comment by jb-alvarado** [comment] 2015-09-17 18:15
Interesting. When I had try it, it had not work. And when you google about it, people say you need tee, or a selfmade tee.bat

**Comment by wiiaboo** [comment] 2015-09-17 18:19
Oh, but I mean just redirecting to those files, not showing again in the console. That's what I mean by just using bash.exe and hiding everything (just for those initial scripts you just run once).

**Comment by jb-alvarado** [comment] 2015-09-17 18:21
Ah, I thought for a moment you are able to do both. Only a output in the logfile is to "danger", what is if the bash process hangs somewhere, then you wait hours for nothing :).

**Comment by wiiaboo** [comment] 2015-09-17 18:28
We could use those redirections inside the .sh themselves instead of bash.exe. Then we still wouldn't need mintty and in case something goes wrong it'll probably tell something?

**Comment by jb-alvarado** [comment] 2015-09-17 18:33
Then you have to make after every command a write statement to the logfile. Is a bit to complicate, I think. Ok for the little scripts is not so much, but the bigger ones.

**Comment by wiiaboo** [comment] 2015-09-17 18:34
Of course, I'm talking about the little scripts only. The other's (update.sh and compile.sh) use mintty and its --log option.

**Comment by jb-alvarado** [comment] 2015-09-17 18:37
Yes that sound good. And you think this works to, when the update.sh script hangs? You has made a command there, that It must be close manually.

**Comment by wiiaboo** [comment] 2015-09-17 19:24
I am waiting for when there's an update to bash to try that. The new base doesn't need any update to those three critical one so it doesn't have problems closing on its own.
