### ISSUE TITLE
x265 compilation error

### ISSUE THREAD

**Issue by Barough** [jb-alvarado/media-autobuild_suite#886] opened 2018-07-27 15:12 UTC
Running hg update for x265...
┌ x265 hg .............................................. [Updates found]
├ Running uninstall...
├ Building 12-bit lib for multilib...
├ Running cmake...
Likely error:
CFLAGS: -mthreads -mtune=generic -O2 -pipe
LDFLAGS: -pipe -static-libgcc -static-libstdc++
cmake /build/x265-hg/source -G Ninja -DCMAKE_INSTALL_PREFIX=/local32 -DBIN_INSTALL_DIR=/local32/bin-video -DENABLE_SHARED=OFF -DENABLE_CLI=OFF -DHIGH_BIT_DEPTH=ON -DHG_EXECUTABLE=/usr/bin/hg.bat -DENABLE_HDR10_PLUS=ON -DENABLE_ASSEMBLY=OFF -DEXPORT_C_API=OFF -DMAIN12=ON
D:/media-ab_suite/msys64/mingw32/bin/cmake.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
cmake failed. Check D:/media-ab_suite/build/x265-hg/build-32bit/12bit/ab-suite.cmake.log
This is required for other packages, so this script will exit.
  Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/sVDH.zip

**Comment by wiiaboo** [comment] 2018-07-27 16:44
Duplicate of https://github.com/jb-alvarado/media-autobuild_suite/issues/885

**Closed by wiiaboo** 2018-07-27 16:44 UTC
