### ISSUE TITLE
Build seems to be broken after msys update

### ISSUE THREAD

**Issue by BlackScreen** [jb-alvarado/media-autobuild_suite#469] opened 2017-02-14 13:04 UTC
After the latest update of msys, the suite build function seems to be broken.
The output is the following:

>         Starting 64bit compilation of all tools
> Imported default FFmpeg options from .bat
> License: nonfree
> Imported default mpv options from .bat
> 
>         Starting 64bit compilation of global tools
> warning: Public keyring not found; have you run 'pacman-key --init'?
> error: GPGME error: Invalid crypto engine
> warning: Public keyring not found; have you run 'pacman-key --init'?
> error: GPGME error: Invalid crypto engine
> warning: Public keyring not found; have you run 'pacman-key --init'?
> error: GPGME error: Invalid crypto engine
> freetype2 2.7 .......................................... [Not installed]
> ├ Running extract...
> /build/media-suite_helper.sh: line 55: cd: freetype-2.7: No such file or directory
>   Creating diagnostics file...
> warning: Public keyring not found; have you run 'pacman-key --init'?
> error: GPGME error: Invalid crypto engine
> warning: Public keyring not found; have you run 'pacman-key --init'?
> error: GPGME error: Invalid crypto engine
> warning: Public keyring not found; have you run 'pacman-key --init'?
> error: GPGME error: Invalid crypto engine
> warning: Public keyring not found; have you run 'pacman-key --init'?
> error: GPGME error: Invalid crypto engine
> warning: Public keyring not found; have you run 'pacman-key --init'?
> error: GPGME error: Invalid crypto engine
> warning: Public keyring not found; have you run 'pacman-key --init'?
> error: GPGME error: Invalid crypto engine
> 
> Failed changing to directory freetype-2.7.
>

**Comment by BlackScreen** [comment] 2017-02-14 13:19
I also found out, that the "ffmpeg_options.txt" is missing in my build path.
Is the file not created automatically? Do I have to create myself?

**Comment by wiiaboo** [comment] 2017-02-14 13:20
Depends on what you selected for `ffmpegChoice`. If anything but `1`, then you don't need a ffmpeg_options.txt, since you chose a base preset of options.

**Comment by BlackScreen** [comment] 2017-02-14 13:31
Ok, that I understood. Have checked it with a clean install. Works. So thanks for that! :)
The other problem, mentioned in the first post, is still existing with the clean install.

**Comment by wiiaboo** [comment] 2017-02-14 13:40
GPGME is a known issue, but not the suite's fault. It could be anything's fault, from conflicting libs in your system to some error that occurred in installing.

I can't guess what's wrong in your system without the logs.zip or at least the diagnostics.txt. Either upload them or complain in [MSYS2](https://github.com/Alexpux/MSYS2-packages/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20GPGME%20error) directly and close this issue.

**Comment by BlackScreen** [comment] 2017-02-14 14:05
Hm. I don't think it is my system. I did not change anything. The only thing was the updated msys...
I can not give you the normal "logs.zip" as the suite stops after output in post 1. I have zipped everything from the "build"-folder and uploaded it for you: http://www.filedropper.com/manuallogs
Thank you for looking into it!

**Comment by wiiaboo** [comment] 2017-02-14 14:07
Have you tried opening mintty and running `pacman-key --init` like the error suggests?

**Comment by BlackScreen** [comment] 2017-02-14 14:14
Yeah, I did try that...
```
$ pacman-key --init
C:/Users/XXX/Downloads/media-autobuild_suite-master/msys64/usr/bin/gpg.exe: error while loading shared libraries: msys-readline7.dll: cannot open shared object file: No such file or directory
chmod: cannot access '/etc/pacman.d/gnupg/trustdb.gpg': No such file or directory
C:/Users/XXX/Downloads/media-autobuild_suite-master/msys64/usr/bin/gpg.exe: error while loading shared libraries: msys-readline7.dll: cannot open shared object file: No such file or directory
C:/Users/XXX/Downloads/media-autobuild_suite-master/msys64/usr/bin/gpg.exe: error while loading shared libraries: msys-readline7.dll: cannot open shared object file: No such file or directory
==> Updating trust database...
C:/Users/XXX/Downloads/media-autobuild_suite-master/msys64/usr/bin/gpg.exe: error while loading shared libraries: msys-readline7.dll: cannot open shared object file: No such file or directory
==> ERROR: Trust database could not be updated.

```

**Comment by wiiaboo** [comment] 2017-02-14 14:15
Try `pacman -S --force libreadline`.

**Comment by BlackScreen** [comment] 2017-02-14 14:18
Sadly, no success...

```
$ pacman -S --force libreadline
warning: Public keyring not found; have you run 'pacman-key --init'?
error: GPGME error: Invalid crypto engine
warning: Public keyring not found; have you run 'pacman-key --init'?
error: GPGME error: Invalid crypto engine
warning: Public keyring not found; have you run 'pacman-key --init'?
error: GPGME error: Invalid crypto engine
error: database 'mingw32' is not valid (invalid or corrupted database (PGP signature))
error: database 'mingw64' is not valid (invalid or corrupted database (PGP signature))
error: database 'msys' is not valid (invalid or corrupted database (PGP signature))
```

**Comment by wiiaboo** [comment] 2017-02-14 14:19
This is likely caused by the split pacman install that need to be done for Windows 7 only. Dependees of libreadline were installed before libreadline itself so they errored out.

What does `pacman -Quq` say?

**Comment by schmitti73** [comment] 2017-02-14 14:22
i did copy msys-readline6.dll to msys-readline7.dll
now, it seems working.

**Comment by wiiaboo** [comment] 2017-02-14 14:23
Heh. Now you do need `pacman -S --force libreadline` so it doesn't error replacing that msys-readline7.dll file

**Comment by wiiaboo** [comment] 2017-02-14 14:24
I was going to suggest going to `msys64\var\cache\pacman\pkg\libreadline-7.0.003-1-x86_64.pkg.tar.xz` and extracting the .dll files to `msys64\usr\bin\`.

**Comment by schmitti73** [comment] 2017-02-14 14:24
i had the same prob, but after my copy it started to work. maybe another git repo updated in parallel?

**Comment by wiiaboo** [comment] 2017-02-14 14:29
pacman fails sometimes in Win7 if you pass a large amount of packages to install, so this split is probably still needed. It should happen rarely since packages don't usually change major version.

**Comment by BlackScreen** [comment] 2017-02-14 14:50
```
$ pacman -Quq
warning: Public keyring not found; have you run 'pacman-key --init'?
error: GPGME error: Invalid crypto engine
warning: Public keyring not found; have you run 'pacman-key --init'?
error: GPGME error: Invalid crypto engine
warning: Public keyring not found; have you run 'pacman-key --init'?
error: GPGME error: Invalid crypto engine
error: database 'mingw32' is not valid (invalid or corrupted database (PGP signature))
error: database 'mingw64' is not valid (invalid or corrupted database (PGP signature))
error: database 'msys' is not valid (invalid or corrupted database (PGP signature))
```

Your suggestion with extracting the dlls from msys64\var\cache\pacman\pkg\libreadline-7.0.003-1-x86_64.pkg.tar.xz does not work, because I do not have the file there.

Copying the msys-readline6.dll to msys-readline7.dll did not really work for me.
When starting the script I get: "error: mingw32: key "5F92EFC1A47D45A1" is unknown" and a few other errors. So this does not really work.

**Comment by wiiaboo** [comment] 2017-02-14 14:51
You can download it from http://repo.msys2.org/msys/x86_64/libreadline-7.0.003-1-x86_64.pkg.tar.xz

**Comment by schmitti73** [comment] 2017-02-14 14:55
i did:
# purge all olders
# start the .bat file
# shortly after msys availablity => copy readline6 to readline7
# look at build window

**Comment by wiiaboo** [comment] 2017-02-14 15:05
You might want to try commenting the split package behavior in media-suite_update.sh by adding a `#` before the text in line 21, since it seems to only happen when reaching that point of the build.

**Comment by BlackScreen** [comment] 2017-02-14 16:19
All methods mentioned above do not solve the problem. :(
I get the following output in the update suite window (the output is very slow):
```
-------------------------------------------------------------------------------
Updating pacman database...
-------------------------------------------------------------------------------

error: mingw32: key "5F92EFC1A47D45A1" is unknown
error: key "5F92EFC1A47D45A1" could not be looked up remotely
error: mingw64: key "5F92EFC1A47D45A1" is unknown
error: key "5F92EFC1A47D45A1" could not be looked up remotely
error: msys: key "5F92EFC1A47D45A1" is unknown
error: key "5F92EFC1A47D45A1" could not be looked up remotely
:: Synchronizing package databases...
 mingw32                                        315.7 KiB   700K/s 00:00 [#######################################] 100%
 mingw32.sig                                     96.0   B  0.00B/s 00:00 [#######################################] 100%
error: mingw32: key "5F92EFC1A47D45A1" is unknown
error: key "5F92EFC1A47D45A1" could not be looked up remotely
error: failed to update mingw32 (invalid or corrupted database (PGP signature))
 mingw64                                        315.6 KiB   701K/s 00:00 [#######################################] 100%
 mingw64.sig                                     96.0   B  0.00B/s 00:00 [#######################################] 100%
error: mingw64: key "5F92EFC1A47D45A1" is unknown
error: key "5F92EFC1A47D45A1" could not be looked up remotely
error: failed to update mingw64 (invalid or corrupted database (PGP signature))
 msys                                           139.6 KiB   472K/s 00:00 [#######################################] 100%
 msys.sig                                        95.0   B  0.00B/s 00:00 [#######################################] 100%
error: msys: key "5F92EFC1A47D45A1" is unknown
                                                                                                                       error: key "5F92EFC1A47D45A1" could not be looked up remotely
error: failed to update msys (invalid or corrupted database (PGP signature))
error: failed to synchronize any databases
error: failed to init transaction (invalid or corrupted database (PGP signature))
error: mingw32: key "5F92EFC1A47D45A1" is unknown
error: key "5F92EFC1A47D45A1" could not be looked up remotely
error: mingw64: key "5F92EFC1A47D45A1" is unknown
error: key "5F92EFC1A47D45A1" could not be looked up remotely
error: msys: key "5F92EFC1A47D45A1" is unknown
error: key "5F92EFC1A47D45A1" could not be looked up remotely
```

**Comment by BlackScreen** [comment] 2017-02-14 16:29
And in the build window...

```
        Starting 64bit compilation of all tools
Imported FFmpeg options from ffmpeg_options.txt
License: nonfree
Imported mpv options from mpv_options.txt

        Starting 64bit compilation of global tools
error: mingw32: key "5F92EFC1A47D45A1" is unknown
error: key "5F92EFC1A47D45A1" could not be looked up remotely
error: mingw64: key "5F92EFC1A47D45A1" is unknown
error: key "5F92EFC1A47D45A1" could not be looked up remotely
error: msys: key "5F92EFC1A47D45A1" is unknown
error: key "5F92EFC1A47D45A1" could not be looked up remotely
freetype2 2.7 .......................................... [Not installed]
├ Running extract...
/build/media-suite_helper.sh: line 55: cd: freetype-2.7: No such file or directory
  Creating diagnostics file...
error: mingw32: key "5F92EFC1A47D45A1" is unknown
error: key "5F92EFC1A47D45A1" could not be looked up remotely
error: mingw64: key "5F92EFC1A47D45A1" is unknown
error: key "5F92EFC1A47D45A1" could not be looked up remotely
error: msys: key "5F92EFC1A47D45A1" is unknown
error: key "5F92EFC1A47D45A1" could not be looked up remotely
error: mingw32: key "5F92EFC1A47D45A1" is unknown
error: key "5F92EFC1A47D45A1" could not be looked up remotely
error: mingw64: key "5F92EFC1A47D45A1" is unknown
error: key "5F92EFC1A47D45A1" could not be looked up remotely
error: msys: key "5F92EFC1A47D45A1" is unknown
error: key "5F92EFC1A47D45A1" could not be looked up remotely

Failed changing to directory freetype-2.7.
```

**Comment by wiiaboo** [comment] 2017-02-14 16:34
1. completely remove msys64
2. make sure you applied that change to media-suite_update.sh (you can also remove the whole line
   - make sure it's the line with `[[ "$(uname)" = *6.1* ]] && nargs="-n 4"`. Delete it or add a `#` before.
3.  after the change is done and msys64 is removed, run the .bat. It'll download everything again but maybe without that line in media-suite_update.sh it won't cause trouble this time.

**Comment by BlackScreen** [comment] 2017-02-14 16:56
Ok, I did exactly what you said and it seems to have fixed it.
The build is running right now, but without the errors I got earlier. Thanks!

**Comment by wiiaboo** [comment] 2017-02-14 16:57
Would be a good idea to uncomment/readd the line though, unless you update to Win8/10 meanwhile, or you'll get the same GPGME errors eventually.

**Closed by wiiaboo** 2017-02-14 16:57 UTC

**Comment by BlackScreen** [comment] 2017-02-15 08:30
Ok, so if I understand you correctly, if I stay on Windows 7, I would have to leave the line commented out?
Would there be a way for the suite to detect the windows version and uncomment or comment out the line according to the Windows version?

**Comment by wiiaboo** [comment] 2017-02-15 12:57
Uncomment the line if you stay in Win7.
`[[ "$(uname)" = *6.1* ]] && nargs="-n 4"`
The first part checks for version 6.1 of NT (Windows 7). It's specifically something that only Win7 requires.

**Comment by BlackScreen** [comment] 2017-02-15 13:18
Ok, perfect. Thanks for clarifying. :)
